### PR TITLE
Add keyboard navigation in SideNav, SideNavFilter, and NoteList

### LINKED ISSUE #271: Shortcuts for moving folder
Hi, I want shortcuts for moving folder like moving notes. I suggest `Ctrl + Shift + U` and `Ctrl + Shift + J`.

### PR DESCRIPTION
**Pull request by justin-calleja**
Closes #271 (I think)

issue-271

1. up / down on storage items and their folders work, including moving between storages and looping back to SideNavFilter items.
2. shift + left closes the current storage if you're on a storage item or a folder within the storage item
3. shift + right opens the current storage if you're on a storage
4. ctrl + shift + left closes all storages (even if you're on a SideNavFilter item)
5. ctrl + shift + right opens all storages (even if you're on a SideNavFilter item)
6. There is some visual indication when focus is gained and lost in the SideNav (and NoteList). When there is focus, you can use these keyboard shortcuts to navigate.
7. left / right move between SideNav (or SideNavFilter) and NoteList.

### CODE REVIEW

**Comment by asmsuechan** [comment]
Hi, @justin-calleja! Thank you for great PR! I think this feature is good for us :smile: But I have a favor for you. Could you separate the commit? It's too heavy.

**Comment by justin-calleja** [comment]
@asmsuechan sure thing. Would the following work? (each point a separate commit):

* up / down across SideNav items and SideNavFilter
* collapse expand one / collapse expand all SideNav items
* navigate between SideNav items and NoteList items

**Comment by asmsuechan** [comment]
@justin-calleja Yes, they all work fine.

**Comment by justin-calleja** [comment]
@asmsuechan ok cool. I'll split it in 3 commits.

**Comment by justin-calleja** [comment]
@asmsuechan it's split in 4 ("Add mainProcessArgs helper..." one is for dev purposes (adds Redux dev tools if --hot is used)).

Hope this is better. Thanks!

**Comment by justin-calleja** [comment]
@asmsuechan disregard this PR for now. I failed to "test" Finger pop up.

**Comment by justin-calleja** [comment]
@asmsuechan ok fixed in last commit. Basically it was accessing `focus.sideNav` or `focus.noteList`. In Finder... `focus` is not being passed in (didn't work on Finder part - TODO).

I changed all components to just take in their focus of interest (sideNav v.s. noteList) directly. That way, not passing in a value becomes false...

end result - no error when you start up Finder. But yes, Finder does not yet support keyboard navigation.... I'll work on this later.

**Comment by kazup01** [comment]
What is this status now?

**Comment by justin-calleja** [comment]
@kazup01 sorry I neglected this...

Currently, this can no longer be merged in - not until conflicting files are fixed. Even if it's merged, I never implemented the same keyboard shortcuts for the Finder window (was new to Boostnote and didn't even use that window tbh).

If you guys are interested in merging this, I can resume working on it some time soon (this weekend).

**Comment by kazup01** [comment]
No problem, thanks again for your help! @justin-calleja 

This feature is awesome, so we want to merge it. Could you resume?
We will update to next version in two weeks, so you don't need to rush.

**Comment by justin-calleja** [comment]
@kazup01 sure, wasn't sure if it'd get merged as interested in it had stopped (I thought I'd let part 1 without the Finder implementation get merged before working on the rest).

Anyway, I'll be looking into this again soon.

**Comment by kazup01** [comment]
Thanks!

**Comment by justin-calleja** [comment]
This PR is being closed because it has been replaced by:

https://github.com/BoostIO/Boostnote/pull/711

**Pull request closed without merging**
