### PR TITLE
Suppport auto generating toc content for the [TOC] tag

### PR DESCRIPTION
**Pull request by hikerpig**
## Description

This PR add a markdown-it plugin to support auto generating content for `[TOC]` or `[toc]` tag.

This feature was implemented in many Markdown editors, (Typora, Haroopad, MWeb, etc.).

Although there is already a command 'Generate/Update Markdown TOC' in Boostnote, but I think these two serve for different purposes, so they can both exist.

The demo goes:

toc-tag-demo

## Issue fixed

-  #3022

## Type of changes

- :radio_button: Feature (Change that adds new functionality)

## Checklist:

- :radio_button: My code follows [the project code style](docs/code_style.md)
- :radio_button: I have written test for my code and it has been tested
- :radio_button: All existing tests have been passed
- :radio_button: I have attached a screenshot/video to visualize my change if possible

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Referenced issues

This pull request has been submitted to:
- [#3022: [TOC] tag support](https://issuehunt.io/repos/53266139/issues/3022)
---

IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### CODE REVIEW

**Comment by ZeroX-DG** [comment]
@hikerpig  thanks for the cool PR, can you add a setting to disable this feature? Some people may not need auto generated toc

**Comment by hikerpig** [comment]
@ZeroX-DG  I don't see your worry here, maybe I misunderstand it.

Let's assume if someone typed this `[TOC]` placeholder - which is not a common word - manually, the expected behavior should be auto generating content.

Say if there is a config and it is turned off, what is the expected behavior for the placholder?

**Comment by ZeroX-DG** [comment]
@hikerpig You can totally ignore my comment, I didn't see the `[toc]` tag. My brain sometimes is on autopilot :smile:

**Comment by hikerpig** [comment]
Code review could be exhausting sometimes 😆 ,  thank you for your work.

Let me know if there is anything else that needs to be updated.

**Comment by amedora** [comment]
looks nice.

However we should remove current implementation of TOC feature before add this new one.

**Comment by ZeroX-DG** [comment]
@amedora can you share your thought on this? Why can't they both exist?

**Comment by ZeroX-DG** [comment]
@hikerpig it seem that your markdownItTocAndAnchor lib doesn't support heading with uppercase letter. Can you fix it please?

**Comment by amedora** [comment]
@ZeroX-DG ,Technically both can exist together.
However, it's questionable to have two implementations for that almost same feature...(is it worth to maintain both codes?)

**Comment by ZeroX-DG** [comment]
@amedora I think we should also keep the old TOC too, because user will have more control/customization of the TOC with the old feature.

**Comment by amedora** [comment]
@ZeroX-DG, I see. Thank you for your clarification :+1:

**Comment by ZeroX-DG** [comment]
@hikerpig ping!

**Comment by hikerpig** [comment]
@Flexo013  What needs to be changed? Should I add anything ?

**Comment by Flexo013** [comment]
There was this comment by Zero:

> @hikerpig it seem that your markdownItTocAndAnchor lib doesn't support heading with uppercase letter. Can you fix it please?

**Comment by hikerpig** [comment]
@ZeroX-DG  I can't reproduce the bug what you described with `heading with uppercase letter`.

Can you be more specific? Give me some example content so I can improve against. 😃

**Comment by ZeroX-DG** [comment]
@hikerpig Here is a small example:
image
As you can see, the id of the actual heading has uppercase letter while in the link it automatically lowercase everything, this make the link not navigate to the heading.

**Comment by hikerpig** [comment]
@ZeroX-DG  Oh I see, I will fix this in 48h.

**Comment by hikerpig** [comment]
@ZeroX-DG  I've update the package to fix this annoying lowercase-casting thing.

**Comment by Rokt33r** [comment]
@hikerpig I want to merge this very soon. Could you fix the conflicts?

**Comment by Rokt33r** [comment]
@hikerpig Could you fix CI error too? I think updating snapshot should be enough! Check https://travis-ci.org/BoostIO/Boostnote/builds/596037299#L394

**Comment by hikerpig** [comment]
Error fixed.

BTW, I suggest that the npm 'test' script should contain jest tests.

**Comment by Rokt33r** [comment]
@hikerpig Thanks! ❤️

**Pull request merged**
