### PR TITLE
Adds vim keymap setting

### PR DESCRIPTION
**Pull request by asmsuechan**
Hello, finally I add vim-keymap to boostnote.

reference: https://codemirror.net/2/demo/vim.html

### CODE REVIEW

**Comment by kazup01** [comment]
Wow great!
I'm so excited.

**Comment by asmsuechan** [comment]
However, we should reload boostnote after change the setting because the keymap itself isn't loaded only by just change `config.editor.keyMap`. Thus I put a note. Please check the sentence also.

**Comment by sota1235** [comment]
This is so cool!! I'll check it.

**Comment by sota1235** [comment]
@asmsuechan Thank you for your contribution. 
The code changed looks good, but I want you fixing more files.
`browser/finder/NoteDetail.js` and `browser/main/Detail/SnippetNoteDetail.js` also use `CodeEditor` component. So please add `keymap` props to them.

**Comment by asmsuechan** [comment]
@sota1235 Thanks for your review, I try to fix them!

**Comment by asmsuechan** [comment]
I added props to them however I cannot figure out why I should add keyMap to browser/finder/NoteDetail.js. I cannot write note on finder.

**Comment by sota1235** [comment]
That's correct specification that you can't edit the note on finder.
So, that should not be focused when the note clicked. It's other problem.

I like vim, so this pull request is like God. Thank you!

**Comment by sota1235** [comment]
Related #146

**Pull request merged**
