### PR TITLE
Feature amazon mobile analytics

### PR DESCRIPTION
**Pull request by sosukesuzuki**
Boostnote collect data by mixpanel, now. But, We want to use amazon mobile analytics for collecting data.

### CODE REVIEW

**Comment by kohei-takata** [comment]
LGTM

**Comment by NicoHood** [comment]
Why do you add spyware to boostnote and collect data? Could you please precise which data is collected and why? Also an option to opt-out would be nice.

**Comment by asmsuechan** [comment]
Hi, @NicoHood. As you can see in this PR, we send events to AWS Mobile Analytics like access counter. It means any note content is sent to it. The reason why we added `spyware` was that because we had to know how many users are using the features such as ADD_MARKDOWN, ADD_SNIPPET, or ADD_FOLDER and so on to improve Boostnote more and more. I hope this answers your question.

**Comment by NicoHood** [comment]
@asmsuechan Thanks for the answer. From my point of view you should:
* Clearly inform the user about this spyware
* Add an option to opt-out

Otherwise people will possibly refuse to use this software. Because those users who want to use free alternatives (like me) will see this as a no-go.

**Comment by asmsuechan** [comment]
@NicoHood What you want is [here](https://github.com/BoostIO/Boostnote/pull/715).

**Pull request merged**
