### PR TITLE
Changed wording in build.md and debug.md

### PR DESCRIPTION
**Pull request by SalvatoreTosti**
I've adjusted the wording in the build and debug files to flow better and make more sense in English.

### CODE REVIEW

**Comment by kazup01** [comment]
Thank you @SalvatoreTosti san!! This is very helpful. I will check it soon.

**Comment by SalvatoreTosti** [comment]
@kazup01 No problem, glad I could help out.

**Comment by kazup01** [comment]
I merged it! Thank you for your cooperation!🎉

**Comment by asmsuechan** [comment]
@SalvatoreTosti Thank you so much!

**Pull request merged**
