### PR TITLE
Implementing a context menu handler to show an attachment in the expl…

### PR DESCRIPTION
**Pull request by ehhc**
It would be nice to open the location of an attachment with the explorer -> Implementing a contextMenu in the MarkdownPreview to do this :)

### CODE REVIEW

**Comment by ehhc** [comment]
@sosukesuzuki but your solution would break it on windows platform.. I will think about a platform independent solution :)

**Comment by ehhc** [comment]
@sosukesuzuki in that case i have no idea why i dosen't work.. on my windows 10 it works .. :( no idea whats different..

**Comment by sosukesuzuki** [comment]
@ehhc Umm..., I have no idea too. I'll put label "help wanted!".

**Comment by ehhc** [comment]
@sosukesuzuki i think the problem may be that i hard-coded the way i removed the file-prefix.. i'm using an library to do so now.. hopefully that solves the issue. Would you do me a huge favor and test it again?

Steps to reproduce:
1. drag&drop a file into the editor
2. Right-click on the link of the attachment in the markdown-preview
3. "Show in explorer" should be visible and should open the explorer at the location of the attachment


Thank you for your help :)

**Comment by ehhc** [comment]
I think the library i'm using now solves exactly your problem (that the paths are different on linux systems).. :)

**Comment by sosukesuzuki** [comment]
@ehhc Confirm that it works on my local environment!(MacOS 10.13.5)

**Comment by ehhc** [comment]
Thanks guys :)

**Pull request merged**
