### PR TITLE
#2194 - fixes Hotkey not working

### PR DESCRIPTION
**Pull request by gurungrahul2**
## Description

It makes possible to use Cmd as abbreviation for setting as hot key.
## Issue fixed

#2194 

## Type of changes

- :black_circle: Bug fix (Change that fixed an issue)
- :white_circle: Breaking change (Change that can cause existing functionality to change)
- :white_circle: Improvement (Change that improves the code. Maybe performance or development improvement)
- :white_circle: Feature (Change that adds new functionality)
- :white_circle: Documentation change (Change that modifies documentation. Maybe typo fixes)

## Checklist:

- :black_circle: My code follows [the project code style](docs/code_style.md)
- :white_circle: I have written test for my code and it has been tested
- :white_circle: All existing tests have been passed
- :white_circle: I have attached a screenshot/video to visualize my change if possible

### CODE REVIEW

**Comment by gurungrahul2** [comment]
@Rokt33r @ZeroX-DG any updates :).

**Comment by gurungrahul2** [comment]
Review ping.

**Comment by ZeroX-DG** [comment]
Sorry for the delay. @Rokt33r is very busy at the moment. Maybe he will review this weekend.

**Comment by gurungrahul2** [comment]
thanks. :)

**Pull request merged**
