### PR TITLE
Refine Chinese translation

### PR DESCRIPTION
**Pull request by andysim3d**
- Should not translate "space", it means space key in most context
- Should translate "keymap", "spellcheck disabled", "auto detect"
- Should translate "On Right Click" to "右键点击"
- Refine misc translation.

## Type of changes

- :white_circle: Bug fix (Change that fixed an issue)
- :white_circle: Breaking change (Change that can cause existing functionality to change)
- :white_circle: Improvement (Change that improves the code. Maybe performance or development improvement)
- :white_circle: Feature (Change that adds new functionality)
- :radio_button: Documentation change (Change that modifies documentation. Maybe typo fixes)

## Checklist:

- :white_circle: My code follows [the project code style](docs/code_style.md)
- :white_circle: I have written test for my code and it has been tested
- :radio_button: All existing tests have been passed
- :white_circle: I have attached a screenshot/video to visualize my change if possible

### CODE REVIEW

**Comment by ZeroX-DG** [comment]
@andysim3d can you introduce someone to review this PR? I need at least 1 more review from other people to approve this PR

**Comment by andysim3d** [comment]
@qz267 could you help?

**Comment by andysim3d** [comment]
Or @silverwzw

**Comment by ZeroX-DG** [comment]
Alright, more reviews are welcome:) I'll let this open for about a week for any more review. If all are happy then we will merge this.

**Pull request merged**
