### PR TITLE
Highlight global search matches on code editor

### PR DESCRIPTION
**Pull request by Redsandro**
I like to see the global search matches in the markdown editor for productivity reasons. I implemented this for personal use, and I hope it will be useful to others.

This partially addresses #755.

This PR makes it more evident that the global search box could really use both an "x" symbol that appears to clean/delete the current input (for touch users) or having the escape key clean the input (for keyboard users), but that is beyond the scope of this PR. See #1525.

### CODE REVIEW

**Comment by Redsandro** [comment]
image

**Comment by sosukesuzuki** [comment]
If we update keyword in search box, code editor is hidden and markdown preview is shown.
This behavior is not great.

**Comment by Redsandro** [comment]
@sosukesuzuki I hadn't observed that. I think it's because I have split view enabled by default, and you have the preview by default.

I can fix this, if you would consider it.

**Comment by Redsandro** [comment]
@sosukesuzuki I have examined this. What you are observing is original behavior by Boostnote. If you search, your list of notes refreshes, the code editor closes, and a new note from the list is viewed in the preview. It was already like this, by design (not by me). 

This PR adds global search highlighing in the code editor. Especially useful in dual pane editing. Whether or not the editor should close when search is used, is not decided, designed, or changed by this PR. It is also not in the scope of this PR.

If the note selected by search should be opened in the code editor by default (e.g. when the code editor was previously selected), this should be a different PR or feature request.

Please consider merging this PR as it will be useful for some, and consider writing a PR for the extra features you think would be useful to others as a result of the functionality this PR brings to the table.

**Pull request merged**
