### PR TITLE
[Refactor] Use ESLint instead of StandarJS and add settings for TravisCI

### PR DESCRIPTION
**Pull request by sota1235**
# Update

- Use ESLint for checking coding style.
- Add config for using TravisCI.
- Ignore invalid tests. Fix them after...

### CODE REVIEW

**Comment by asmsuechan** [comment]
Hi @sota1235, after this PR was merged, a hot key Toggle Finder(popup) doesn't work properly at least in my environment. Can you check it?

**Comment by asmsuechan** [comment]
This commit 5c7804fc40d26e3254d506d741700ed4eb3299a5 is doubtful.

**Comment by sota1235** [comment]
Oh, I'm sorry. I'll fix it :bow:

**Comment by sota1235** [comment]
I revert this commit, but I can't fix this bug.
I try to investigate this bug and fix it on next release.

**Comment by asmsuechan** [comment]
In my environment, I can fix it by revert the commit. Did you try to restart electron?

**Comment by asmsuechan** [comment]
Oh, I also fail to fix it by revert now 😨

**Pull request merged**
