### PR TITLE
#595 - Resize an image with markdown

### PR DESCRIPTION
**Pull request by dangvanthanh**
- Update resize an image with markdown #595
- Use

```markdown
![](/path/to/image.png =100x200)
```

### CODE REVIEW

**Comment by kazup01** [comment]
Wow @dangvanthanh san, thank you for your cooperation everyday! We will check it!

**Comment by kazup01** [comment]
Cool!

**Comment by darkomen** [comment]
great!!! Thanks you very much!

**Comment by joelcwe** [comment]
@aquCHAOS i think you can leave the width out and it should scale correctly.
`` image.png =100x  ``

**Pull request merged**
