### PR TITLE
fix: #288 Fixed Snippet tabs overwriting other tabs when closed

### PR DESCRIPTION
**Pull request by redcom**
I also replaced the let with const because that is best practices. If the variable shape does not change it should be a const[ant]

### CODE REVIEW

**Comment by asmsuechan** [comment]
According to this comment https://github.com/BoostIO/Boostnote/issues/288#issuecomment-288373268, do you still fail to run the electron app?

**Comment by asmsuechan** [comment]
screen shot 2017-03-22 at 09 24 53

**Comment by redcom** [comment]
How does it look now?

**Comment by redcom** [comment]
screen shot 2017-03-22 at 17 49 24
my issue looks more like the above

**Comment by asmsuechan** [comment]
Did you run `npm install`?

**Comment by redcom** [comment]
Yes. I made another pull request. One has to run the webpack and npm start to get the application running. For the future you can use parallelshell to run 2 command lines at the same time.

**Pull request closed without merging**
