### PR TITLE
[WIP] Make DOUBLECLICK work

### PR DESCRIPTION
**Pull request by asmsuechan**
# context
image

0ac926a007749b18317329e36683e44f

### CODE REVIEW

**Comment by asmsuechan** [comment]
# note
I have to check the behavior of SnippetNoteDetail if a snippet is a markdown snippet.

**Comment by kazup01** [comment]
Hi @asmsuechan , how about this state?

**Comment by asmsuechan** [comment]
I close this until when I have enough time to tackle.

**Comment by kazup01** [comment]
We are waiting for you to get back and drink beer together. @asmsuechan

**Pull request closed without merging**
