### PR TITLE
added shortcut ctrl+q for quit and quit the app when using the Windows Close button

### LINKED ISSUE #997: Application stays running after attempting to close (Windows 10)
Screenshot of the application with the developer tools open as requested:

image

Screenshot after closing:

image

I've tried closing the application in the following ways:
* Clicking the top-right X in Windows
* Hovering over the application in the taskbar and clicking the X in the preview
* Right-clicking the application in the taskbar and clicking 'Close window'

What **does** work is closing is by going through the UI menus Boostnote > Exit.

### PR DESCRIPTION
**Pull request by mslourens**
Fixes #997 

**Changes:**
- added a shortcut (like mentioned in the comments of the issue) CTRL/CMD+Q to quit the app.
- close the app (instead of minimize) when clicking the close button (could be changed in a setting in the future).

### CODE REVIEW

**Comment by kazup01** [comment]
Hi @mslourens , could you fix CI error?

**Comment by mslourens** [comment]
I am not sure why CI failed with the error message: 

> An error occurred while generating the build script.

Can somebody who knows the build process have a look? I just fixed the lint warnings generated by my previous change.

**Comment by kazup01** [comment]
Hi @mslourens , thanks for your check! I could fix it when I restarted the CI. Sorry for your inconvenience. 
We will check it at Sunday. Thanks! :)

**Comment by sota1235** [comment]
@kazup01 Can you confirm how this PR works? If it is fine, please merge it.

**Comment by kazup01** [comment]
Merged.

**Pull request merged**
