### PR TITLE
Export fonts

### PR DESCRIPTION
**Pull request by shmolf**
## Description
Defines a directory within `css` when exporting to HTML. The `fonts` directory includes files used by Katex, MaterialIcons, and Font Awesome.

This is related to the export of HTML and PDF.

[Good PDF Export](https://github.com/BoostIO/Boostnote/files/4006744/GoodExport.pdf) from this update compared to a [Bad PDF Export](https://github.com/BoostIO/Boostnote/files/4006745/BadExport.pdf) from current state.

[Good HTML Export](https://github.com/BoostIO/Boostnote/files/4006748/GoodExport.zip) from this update compared to a [Bad HTML Export](https://github.com/BoostIO/Boostnote/files/4006746/BadExport.zip) from the current state.

## Issue fixed
- [Anchor Issue](https://github.com/BoostIO/Boostnote/issues/3396)
- Handles the export of fonts that originate from within the application, but does not handle OS fonts. So only partially covers https://github.com/BoostIO/Boostnote/issues/1637
- Fixes https://github.com/BoostIO/Boostnote/issues/3127
- The rendering of Formulas were already fixed, but the Fonts and Admonitions mentioned in https://github.com/BoostIO/Boostnote/issues/3202 are fixed with this PR

## Type of changes

- :radio_button: Bug fix (Change that fixed an issue)
- :white_circle: Breaking change (Change that can cause existing functionality to change)
- :radio_button: Improvement (Change that improves the code. Maybe performance or development improvement)
- :white_circle: Feature (Change that adds new functionality)
- :white_circle: Documentation change (Change that modifies documentation. Maybe typo fixes)

## Checklist:

- :radio_button: My code follows [the project code style](docs/code_style.md)
- :white_circle: I have written test for my code and it has been tested
- :radio_button: All existing tests have been passed
- :radio_button: I have attached a screenshot/video to visualize my change if possible

### CODE REVIEW

**Comment by shmolf** [comment]
@ZeroX-DG I think it's safe to say this won't make the v14 release. Do you know about when the next minor/major release would be?

**Comment by ZeroX-DG** [comment]
@shmolf sorry for the late response. I'm still investigating why your PR didn't work on my machine. Everything looks fine when they load to HTML but somehow my PDF export still have broken font

**Comment by ZeroX-DG** [comment]
I discovered that the Katex css didn't even loaded therefore the font didn't get to loaded. But when I open the dev tool and format the Katex css file the view reloaded and everything is ok again. Could very be a Chrome bug.

**Comment by shmolf** [comment]
@ZeroX-DG I've looked at the file using Adobe PDF reader to inspect the document properties. It shows the fonts as being embedded in the document.

image

It could be that the PDF export on different OS's is inconsistent. It does rely on the Print functionality.

There was a merge conflict, and so I'm pushing changes for the merge conflict.

**Comment by ZeroX-DG** [comment]
@shmolf I tried to print multiple time and sometime the normal content of the note didn't get to load, sometime the katex is not display and sometime it produce a blank space. When the content of the note did get loaded I check the font property and there's only the font for that text appears, but when only the katex element is displayed, only katex fonts appears. I think this is a chrome bug, if you dont destroy the new window used for printing you will see that sometime the css is not getting loaded therefore it display the whole thing as plain text and no font are getting loaded in the network tab too.

Should we change to something  else, is there any other option for printing PDF?

**Comment by shmolf** [comment]
I'm going to close this PR. We can re-open if it turns out the necessary change can be easily applied to this branch.

But for now, I'm going to start fresh, and look for a different approach. I'd prefer to use chromium's native PDF print capability, rather than a library. But I'll submit a new PR as a replacement for this when I'm finished.

**Pull request closed without merging**
