### PR TITLE
implemented feature request issue#2533

### PR DESCRIPTION
**Pull request by mehr-licht**
I implemented the feature request on issue#2533.

Now either on Markdown Note or on Snippet Note, when entering ctrl+I it shows the Info panel.

cheers

### CODE REVIEW

**Comment by ZeroX-DG** [comment]
@mehr-licht Can you fix the eslint error?

**Comment by mehr-licht** [comment]
Hi.

Everything is OK on this side.
Yesterday I have initiated on the wrong folder and then did some copy/pasting of files....

Today I've did everything from scratch. Can you please retry. (Do I need to Request a new Pull ?)

yarn test

**Comment by ZeroX-DG** [comment]
@mehr-licht there's nothing wrong with your test. You need to fix your code style to match eslint rules. You can run:
```
npm run lint
```
and the error will display. You can also run the command below to automatically fix those error (there may be some error that needs to be manually fixed)
```
npm run fix
```

**Comment by ZeroX-DG** [comment]
I've seen your new PR, I'll close this PR and review the latest one

**Pull request closed without merging**
