### PR TITLE
allow publishing markdown to wordpress

### PR DESCRIPTION
**Pull request by lurong-hkg**
https://github.com/BoostIO/Boostnote/issues/1571
Scope:
This PR aims to allow users publish `markdown` notes to configured wordpress sites. Snippets are not supported (we should probably allow publishing them to gist)

Feature:
- Publish Markdown document to Wordpress blog
- 2 Authentication methods are supported [JWT token ](https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/) or [WP-API basic auth](https://github.com/WP-API/Basic-Auth)
- Update published Blog
- Open published Blog

Requirements
- Wordpress rest api [doc](https://developer.wordpress.org/rest-api/)
- Authentication in wordpress

Screenshots:
- Configuration
image

- Context Menu (Unpublished Markdown)
image

- Context Menu (Published Markdown)
image

- Publish Confirmation
image

- Publish failure comfirmation
image

- Published Blog Sample
image

### CODE REVIEW

**Comment by RomanKlopsch** [comment]
good job!

**Comment by Rokt33r** [comment]
We probably want similar things for Ghost and any other blogging platform. Let us think this for several days.

**Comment by Rokt33r** [comment]
We're gonna accpet this and ship to the next version. 🎉 🎉 🎉 
Thanks for your contribution!!

**Comment by lurong-hkg** [comment]
@Rokt33r will it be in 0.11 or 0.12?

**Comment by Rokt33r** [comment]
@lurong-hkg It will be in v0.11. 👍

**Comment by Rokt33r** [comment]
@lurong-hkg Could you add some documentation about authentication? Or some kind of tooltip in Blog tab should be nice.

If you can afford to do, let me know and create another PR! 😄

**Comment by Rokt33r** [comment]
And we should figure out how we can send images in note.

**Comment by lurong-hkg** [comment]
Correct me if I'm wrong but in Markdown, by inserting image/video means inserting a link to the media. When the markdown is rendered to html, the link persists and will be shown on webpage accordingly as a html media tag. Is there any other cases I'm missing here?

**Comment by Rokt33r** [comment]
I mean local images. :smile: Storage of boostnote can persist images locally! So, we need to check the url of images and upload it to wordpress if it start with `file://...`.

**Comment by lurong-hkg** [comment]
make sense, I'll see if I can convert them to data url.

**Comment by phantomlution** [comment]
@lurong-hkg this feature is quite useful. But I got one issue. The tag I made at Boostnote is never synced to Wordpress. Can you fix that?

image

**Comment by infophile** [comment]
Thank you for this great feature!

However I don't succeed to make the [JWT authentification](https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/) works.
I do the configuration in wp-config.php and I have the namespace and endpoints I guess.
But how can I get the token to fill in Boostnote next ?
What am I suppose to do with this function ?

`( function() {

  var app = angular.module( 'jwtAuth', [] );

  app.controller( 'MainController', function( $scope, $http ) {

    var apiHost = 'http://yourdomain.com/wp-json';

    $http.post( apiHost + '/jwt-auth/v1/token', {
        username: 'admin',
        password: 'password'
      } )

      .then( function( response ) {
        console.log( response.data )
      } )

      .catch( function( error ) {
        console.error( 'Error', error.data[0] );
      } );

  } );

} )();
`

**Comment by Flexo013** [comment]
@infophile Boost Note.next does not have this feature yet. For now it is only part of Boostnote Legacy.

**Pull request merged**
