### PR TITLE
Fix errors when saving a blank hotkey

### PR DESCRIPTION
**Pull request by samherrington**
Saving a blank hotkey showed false error even though hotkey was
saved. This solution solves the issue as it stands, but I
would recommend looking into cleaning up the error handling
surrounding this functionality before adding any new hotkey
fields.

Refs #2153

### CODE REVIEW

**Comment by samherrington** [comment]
This also satisfies #2087, I think.

**Comment by jacobherrington** [comment]
@ZeroX-DG I am fairly sure the error messages correctly reflect what is happening now. If the success message shows up, the hotkey seems to be consistently set to what is in the text box.

**Comment by ZeroX-DG** [comment]
Well, clearly that's the current behavior :smile: Or we will have to prevent users from saving blank hotkeys, however, there're requests that people want to "disable" that hotkey by leaving it blank. So do you have other ideas other than sticking to the current behavior? If not then I think showing a message to notify the user is not a bad idea.

**Comment by samherrington** [comment]
@ZeroX-DG The new behavior allows users to save blank hotkeys and displays the success message when they do (because they have successfully saved a blank hotkey). Before this fix, a blank hotkey returned an error.

**Comment by ZeroX-DG** [comment]
boostnote_bug_hotkey
@samherrington is this the intended behavior?

**Comment by samherrington** [comment]
@ZeroX-DG No, with this PR you should see "Successfully applied!" when either or both of the hotkeys are blank.

**Comment by ZeroX-DG** [comment]
Haha @jacobherrington TIL

**Pull request merged**
