### PR TITLE
Fix scroll sync

### LINKED ISSUE #3512: When scrolling in split-view, editor flickers and doesn't sync with preview
# Current behavior
When scrolling on the preview side, the editor flickers / disappears until I click on it again
image

When scrolling on either side, the other view doesn't sync its position
image

# Expected behavior

- Editor should not flicker / disappear when scrolling
- Each view should sync its position when scrolling 

# Steps to reproduce

1. Access a note long enough to scroll on each side
2. Get in split-view mode
3. Scroll on either sides

# Environment

- Boostnote version: 0.15.1 (_"An open source note-taking app made for programmers just like you."_ How dare you assume what I do !? I feel personnaly offended by this false statement ! 😉
- OS version and name: Windows 10

Let me know if I can help with more screenshots / info :)

### PR DESCRIPTION
**Pull request by Rokt33r**
## Issue fixed

Fixes #3512 

## Type of changes

- :radio_button: Bug fix (Change that fixed an issue)
- :white_circle: Breaking change (Change that can cause existing functionality to change)
- :white_circle: Improvement (Change that improves the code. Maybe performance or development improvement)
- :white_circle: Feature (Change that adds new functionality)
- :white_circle: Documentation change (Change that modifies documentation. Maybe typo fixes)

## Checklist:

- :radio_button: My code follows [the project code style](docs/code_style.md)
- :radio_button: I have written test for my code and it has been tested
- :radio_button: All existing tests have been passed
- :white_circle: I have attached a screenshot/video to visualize my change if possible
- :white_circle: This PR will modify the UI or affects the UX
- :white_circle: This PR will add/update/delete a keybinding

### CODE REVIEW

**Comment by Satanepigone** [comment]
thank you so much! I've been bothered about it for a few weeks.

**Comment by Rokt33r** [comment]
@Satanepigone Sorry for making this mess. I'm glad that you like it.

**Comment by Samsary** [comment]
newbie here

Where can i find this option ? Or how can i turn on it ? 
I am using Windows App version. Boost Note 0.19.0

**Comment by Komediruzecki** [comment]
Hi Samsary,

this github and issue is for legacy boost note application,

The new boost note next application you are using does not support scroll sync in local spaces. But it does in cloud spaces (teams, paid versions, and unpaid restricted version).

If you think this would be a good improvement, please open feature request on this repository: https://github.com/BoostIO/BoostNote.next/issues

So I can look if there is enough interest and implement it for local space as well.

Thank you for your patience!

**Pull request merged**
