### PR TITLE
Fix the search note functionality

### PR DESCRIPTION
**Pull request by richardtks**
## Description

Previously, the search will be executed only when the backspace key is entered. After the fix, the search start as soon as the user enter the character to the input.

fix-search-note

## Issue fixed

#2015 

## Type of changes

- :radio_button: Bug fix (Change that fixed an issue)
- :white_circle: Breaking change (Change that can cause existing functionality to change)
- :white_circle: Improvement (Change that improves the code. Maybe performance or development improvement)
- :white_circle: Feature (Change that adds new functionality)
- :white_circle: Documentation change (Change that modifies documentation. Maybe typo fixes)

## Checklist:

- :radio_button: My code follows [the project code style](docs/code_style.md)
- :white_circle: I have written test for my code and it has been tested
- :radio_button: All existing tests have been passed
- :radio_button: I have attached a screenshot/video to visualize my change if possible

### CODE REVIEW

**Comment by ZeroX-DG** [comment]
I'm not familiar with this CompositionEvent so I'll also need review from @Rokt33r

**Comment by Rokt33r** [comment]
@richardtks I cannot confirm the problem yet. How did you reproduce the problem?

**Comment by Rokt33r** [comment]
@ZeroX-DG Can you reproduce the bug?

**Comment by richardtks** [comment]
@Rokt33r Hi, I able to reproduce by just simply typing the words that I want to search and it did not reflect on the list until I enter backspace.

search_issue

I am using Ubuntu LTS 16.

**Comment by Rokt33r** [comment]
@richardtks Thanks. I'll try again in Ubuntu. 👍

**Comment by richardtks** [comment]
@Rokt33r, I am using ibus. What input system you are using?

**Comment by Rokt33r** [comment]
Hmm... that's weird. I'm using ibus too. Maybe should I check it with Chinese keyboard?

**Comment by richardtks** [comment]
@Rokt33r, weird,  I am using ibus-chinese. maybe this only happens to ibus-chinese....

**Comment by Rokt33r** [comment]
I'm really afraid that this change might interfere with other input system with other languages and other OSs.... Hmm... give me more time to check all of them.

- [ ] Windows / Chinese
- [ ] Windows / Japanese
- [ ] macOS / Chinese
- [ ] macOS / Japanese
- [ ] Ubuntu / Japanese

**Comment by amedora** [comment]
resolved by #3037 already.

**Comment by ZeroX-DG** [comment]
Sorry @richardtks I'll have to close this PR. Thank you very much for the effort anyway :heart:

**Pull request closed without merging**
