### PR TITLE
enable dark mode support for macOS mojave

### LINKED ISSUE #2417: [Feature Request] Support dark mode of MacOS Mojave
On MacOS 10.14 there is now a native dark mode. It would be great if Boostnote would support this dark theme. For example using a dark toolbar at the top and the colors from the dark theme. So Boostnote would be better integrated into the system.

# Environment

- Version : 0.11.9
- OS Version and name : MacOS 10.14

### PR DESCRIPTION
**Pull request by lvarado**
Dark mode support for macOS Mojave was added to `electron-packager` in 12.2.0:
https://github.com/electron-userland/electron-packager/pull/893

This PR updates `electron-packager` and adds the necessary config to the gruntfile.

Before (dark mode enabled):
screen shot 2018-10-19 at 12 11 29 pm

After:
screen shot 2018-10-19 at 12 12 22 pm

Dark mode is automatically used when it is enabled in the system configuration:
screen recording 2018-10-19 at 12 22 21 pm

Fixes #2417

### CODE REVIEW

**Comment by lvarado** [comment]
Note: you need to build the app with `grunt pre-build`. Dark mode will not be enabled if you simply run it with `yarn dev` because `electron-packager` is not used in that case.

**Comment by neha-sri** [comment]
Just a little note for @lvarado - Thank you for this! Waiting for this to be merged and released.

**Comment by Rokt33r** [comment]
Awesome! Could you fix the conflicts? I'll merge this soon.

**Comment by ericsolomon** [comment]
Any update on this?

**Comment by lvarado** [comment]
@Rokt33r @ericsolomon  got the conflicts resolved and cleaned up `yarn.lock` so it only includes hashes present in `master` for a cleaner diff. Should be all set now.

**Comment by lvarado** [comment]
Also related: #1055 and #2318

**Pull request merged**
