### PR TITLE
Fixes search input dropping key input

### PR DESCRIPTION
**Pull request by seanders**
## Description
This PR fixes https://github.com/BoostIo/Boostnote/issues/2843.

The source of the issue seems to have been the asynchronous setting of the component's state. Prior to this change, the search input's state was being updated by a debounced `updateKeyword` function. Pushing these updates to the event queue was causing keystrokes to be lost. The image below should make it more clear:

**Before** this code change:
image
---
**After** this code change:
image

## GIFs
Here is a gif of me trying to type `bacon` as fast as possible

#### Before the fix.
Characters dropped bug

#### After the fix.
Characters dropped bug FIXED

## Issue fixed
https://github.com/BoostIo/Boostnote/issues/2843

## Type of changes

- :radio_button: Bug fix (Change that fixed an issue)
- :white_circle: Breaking change (Change that can cause existing functionality to change)
- :white_circle: Improvement (Change that improves the code. Maybe performance or development improvement)
- :white_circle: Feature (Change that adds new functionality)
- :white_circle: Documentation change (Change that modifies documentation. Maybe typo fixes)

## Checklist:

- :radio_button: My code follows [the project code style](docs/code_style.md)
- :white_circle: I have written test for my code and it has been tested
- :radio_button: All existing tests have been passed
- :radio_button: I have attached a screenshot/video to visualize my change if possible

### CODE REVIEW

**Comment by AWolf81** [comment]
The key dropping with fast typing seems already fixed on master. Can you please double check?

I think there is another issue on master. If you're backspace deleting the text it happens sometimes that the search field is losing focus and the markdown editor text area will be focused instead.

**Comment by e-volusian** [comment]
Has this change been incorporated into the latest release (0.11.16) ? It appears not. Can somebody make it happen? This problem basically makes the search function useless for me.

The problem as I experience it is:
1. Select search field
2. Type something. In my screenshot below, you can see I typed *sqlite*
3. The first part of the search term stays in the search field. The latter part of search term winds up in first line of first result and somehow out of order

<br>

**Comment by fmomin** [comment]
> Has this change been incorporated into the latest release (0.11.16) ? It appears not. Can somebody make it happen? This problem basically makes the search function useless for me.
> 
> The problem as I experience it is:
> 
> 1. Select search field
> 2. Type something. In my screenshot below, you can see I typed _sqlite_
> 3. The first part of the search term stays in the search field. The latter part of search term winds up in first line of first result and somehow out of order
> 
> 
> 
> 
> 
> If nothing else, can the developers maybe consider adding an option to NOT auto-focus the first search result? At least then I could fix the dropped keys without having to switch to the mouse and reselect the search field.

seanders already did the hard work :)
If you are looking to implement this yourself till this is published in new release then:

1. Close boostnote if it is already running
2. Goto "Boostnote\resources\app\compiled"
3. Make a copy of main.js
4. Search for "handleSearchChange" (For me it was line 71755 in version 0.11.15)
5. Add the 3 lines he has added to make the section look like below

	  }, {
	    key: 'handleSearchChange',
	    value: function handleSearchChange(e) {
	      if (this.state.isAlphabet || this.state.isConfirmTranslation) {
					var keyword = this.refs.searchInput.value;
					
					this.setState({
						search: keyword
					})

	        this.updateKeyword(keyword);
	      } else {
	        e.preventDefault();
	      }
	    }
	  }, {

6. Save the file and start Boostnote again
7. Test the change with Developer Tools enabled to ensure it has not broken something else

**Comment by e-volusian** [comment]
@fmomin thanks for the guidance. confirming this fixes the problem for me

**Comment by seanders** [comment]
@Rokt33r @AWolf81 Fwiw, there are still reports of this issue: https://github.com/BoostIO/Boostnote/issues/2843#issuecomment-498040402
Seems like its not yet fixed?

**Comment by Rokt33r** [comment]
AFAIK, https://github.com/BoostIO/Boostnote/pull/3037 fixed this problem. Let me know if it is still broken in master branch. And the fix will be shipped in 2~3 days.

**Comment by seanders** [comment]
@Rokt33r Fair enough. I just wanted to leave a piece of feedback.

I offered up this PR 2 months before the fix in #3037. Personally, I can't help but to admit I find that frustrating. It feels like a lot of wasted time/effort.

This really disinclines me from wanting to make future contributions. I would imagine that this would frustrate future would-be contributors, too.

**Comment by Rokt33r** [comment]
> This really disinclines me from wanting to make future contributions. I would imagine that this would frustrate future would-be contributors, too.

Understood. The problem is I don't have enough time to review prs.. lots of people are using the app though. The good news is I've just started actively preparing the new Boostnote app from this month. But it would take 2~3 months to reveal the new thing from now. I hope you could find us providing better app around end of this October.... I'll do my best. Sorry for disappointing you.

**Pull request closed without merging**
