### PR TITLE
Align notification bar with the navigation bar

### PR DESCRIPTION
**Pull request by sferra**
This fixes the issue of the notification bar convering the "collapse" button of the navigation bar. See #904

### CODE REVIEW

**Comment by kazup01** [comment]
Thanks for your support @sferra ! Could you attach the image?

**Comment by sferra** [comment]
I just noticed that the notification is not centered. I'll try to fix that too.

screenshot from 2017-09-25 17-27-56
screenshot from 2017-09-25 17-27-49

**Comment by sferra** [comment]
The notification is now centered in the notification bar.
screenshot from 2017-09-25 18-47-17

**Comment by kazup01** [comment]
Thanks so much @sferra ! Your PRs are very helpful.

1, Could you fix layout at expand mode?
screen shot 0029-09-26 at 2 18 45 am

2, How do you think about bringing the Notification area to the right? I think this layout looks better.
screen shot 0029-09-26 at 2 24 06 am

Thanks!

**Comment by sferra** [comment]
@kazup01 thanks for testing. i would prefer to address the "notification" position with a separate pull request if that's okay with you. the notification position might be an improvement but it's not related to the actual bug of not being able to toggle the navigation bar.

**Comment by kazup01** [comment]
merged🎉 Thank you for your quick cooperation! @sferra

**Comment by kazup01** [comment]
Could you also send us a PR that fix "notification" to the right side?

**Comment by kazup01** [comment]
This feature has just released at v0.8.16! Thanks!
https://github.com/BoostIO/Boostnote/pull/1027

**Pull request merged**
