### PR TITLE
fix issues #2644 and #2662

### PR DESCRIPTION
**Pull request by roottool**
## Description

Solved #2644 and #2662.
fix-issues-2644-and-2662
The reason for the bug was that inserting unclosed HTML tags into `innerHTML` was automatically closed.
So I modified to use the existing `escapeHtmlCharacters` method only within the ``` range when in "Allow dangerous html tags" mode.

I referred to the following pages.
- [HTML DOM innerHTML Property documentation](https://www.w3schools.com/jsref/prop_html_innerhtml.asp)
- [Javascript - .innerHTML changes auto close tags](https://stackoverflow.com/questions/26728671/javascript-innerhtml-changes-auto-close-tags)

## Issue fixed

[#2644](https://github.com/BoostIO/Boostnote/issues/2644) and [#2662](https://github.com/BoostIO/Boostnote/issues/2662)

## Type of changes

- :radio_button: Bug fix (Change that fixed an issue)
- :white_circle: Breaking change (Change that can cause existing functionality to change)
- :white_circle: Improvement (Change that improves the code. Maybe performance or development improvement)
- :white_circle: Feature (Change that adds new functionality)
- :white_circle: Documentation change (Change that modifies documentation. Maybe typo fixes)

## Checklist:

- :radio_button: My code follows [the project code style](docs/code_style.md)
- :white_circle: I have written test for my code and it has been tested
- :white_circle: All existing tests have been passed
- :radio_button: I have attached a screenshot/video to visualize my change if possible

### Note
I couldn't run the tests.
That's because the following error code has occurred when I executed `npm run test` with Powershell included in Windows 10 Pro.
```
※('PWD' is an internal command or external command,
It is not recognized as an operable program or batch file.)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! boost@0.11.11 test: `PWD=$(pwd) NODE_ENV=test ava --serial`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the boost@0.11.11 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
**The part of ※ was translated by Google translation on what was displayed in Japanese.**

### CODE REVIEW

**Comment by ZeroX-DG** [comment]
Can you tell me the reason why you put the escapeHTML function in the attachmentManagement file?

**Comment by roottool** [comment]
Because I refer to `fixLocalURLS` function in the attachmentManagement file.
I looked at the `fixLocalURLS` function to convert HTML, and I decided to put the escapeHTML function in the attachmentManagement file.

If the place to define the function is the best in `MarkdownPreview.js`, I will rewrite the code.
In that case probably I think that I will define it on line 397 (between `fixDecodedURI` function and `getScrollBarStyle` function).
If there is a better place than that place, I would like you to tell me the place.

**Comment by ZeroX-DG** [comment]
@roottool line 397 sounds good, please rewrite your code.

**Comment by roottool** [comment]
@ZeroX-DG Thank you for review.
I rewrote my code. Please check it again.

**Pull request merged**
