### PR TITLE
Change font color in code at default theme

### PR DESCRIPTION
**Pull request by kazup01**
Like gfm

# Before
screen shot 0029-09-24 at 1 26 00 pm

# After
screen shot 0029-09-24 at 1 22 06 pm

### CODE REVIEW

**Comment by kazup01** [comment]
Merged

**Comment by barkdoll** [comment]
@kazup01 will this be fixed in v0.8.19? The code block font color is still showing pink for me in v0.8.18

**Comment by RyanOakes** [comment]
Like @barkdoll I'm still seeing pink text and would love it if I could just select a text color.

**Comment by barkdoll** [comment]
I can happily report this is working with v0.11.5. Thank you for fixing it! よくやったね… 乾杯！

**Comment by kazup01** [comment]
Thanks @barkdoll :)

**Pull request merged**
