### PR TITLE
iss #832 Make :q work in vim mode

### PR DESCRIPTION
**Pull request by asmsuechan**
# context
We want to exit from the editor in Vim mode.

# before
02a6570e0dd85231d3120aa861a95a83

# after
f76f1b74be813ee10f631b1cd41486d0

# For test
* :q exits from editor mode
* :q! exits from editor mode
* :qw exits from editor mode

### CODE REVIEW

**Comment by kazup01** [comment]
awesome

**Comment by KuangLei** [comment]
May I ask if `:wq` (Save and Exit) works either?  
I know it don't need to be saved manually but saving is a habit for people like me.  

Thanks.

**Comment by asmsuechan** [comment]
Sadly it doesn't work because of https://github.com/codemirror/CodeMirror/blob/25e12b5fe1ee7b0be7e7ee4306608caa4e93c6d6/keymap/vim.js#L701.
It means I can define my own command by only 1 key.

**Comment by KuangLei** [comment]
Thanks very much anyway.

**Comment by KuangLei** [comment]
(It should be `:wq` instead `:qw`.)

**Comment by asmsuechan** [comment]
Exactly :laughing:

**Pull request merged**
