### PR TITLE
Fix font-family at description in snippet

### PR DESCRIPTION
**Pull request by kazup01**

### CODE REVIEW

**Comment by asmsuechan** [comment]
Did you fix the issue? Although I tried it, I didn't see the font change.
screen shot 2017-07-03 at 14 22 28

**Comment by asmsuechan** [comment]
Umm, nothing has changed?
screen shot 2017-07-03 at 22 35 51

**Comment by kazup01** [comment]
u-m

screen shot 0029-07-04 at 1 47 48 am

**Comment by kazup01** [comment]
This is improved by @asmsuechan at #726

**Pull request closed without merging**
