### PR TITLE
Update KaTeX from v0.9.0 to v0.10.0.

### PR DESCRIPTION
**Pull request by Paalon**
It updates KaTeX from v0.9.0 to v0.10.0. Many new features and bug fixes are included.
https://github.com/Khan/KaTeX/blob/master/CHANGELOG.md

### CODE REVIEW

**Comment by Paalon** [comment]
What is this test? Can I overwrite and update them? I think KaTeX changes expression intentionally.

**Comment by ZeroX-DG** [comment]
@Paalon you can run the following command to detect the error:
```
yarn run test
```

**Comment by hzhangxyz** [comment]
I have already commited a similar pull request one month ago. but it is still "in review".

If this this pull request will be merged into master branch successfully, Please consider merging this commit(https://github.com/BoostIO/Boostnote/pull/2411/commits/b1dbd0a54672b2fbfa4a6859f6dc419fe954cb96) to enable global macro in katex.

I am too lazy to keep updating file `tests/lib/snapshots/markdown-test.js.snap`.

**Comment by Paalon** [comment]
Fixed the conflict.

**Comment by omnomz** [comment]
Hi guys, will this PR ever be merged to update KaTeX to v0.10.0?

**Comment by Rokt33r** [comment]
@Paalon Could you fix the conflicts? I'll merge this as soon as you fix the conflicts!

**Comment by Rokt33r** [comment]
Resolved by https://github.com/BoostIO/Boostnote/pull/2998.

**Pull request closed without merging**
