### PR TITLE
Allow preview area to scroll past end of file

### PR DESCRIPTION
**Pull request by allejo**
With regards to #1471... Here's a PR from a complete novice when it comes to the Electron and React world, hope it's not *too* bad. I'm open to learning to the correct way of doing things if you'd be so kind as to point me in the right direction. Anyhow, this worked for me

### CODE REVIEW

**Comment by allejo** [comment]
@sosukesuzuki not sure how that option got there but I updated it to correctly use `config.preview.scrollPastEnd`

**Comment by sosukesuzuki** [comment]
Thanks for your fix!
I'll approve!

**Comment by kazup01** [comment]
Awesome! Thank you @allejo 顔

**Comment by allejo** [comment]
Thank you both! 😄

**Pull request merged**
