### PR TITLE
Blinking markdown crunch fix

### PR DESCRIPTION
**Pull request by max-buranbaev**
I've fixed the issue. Here is a video demo. 
[Video Demonstration](https://www.youtube.com/watch?v=Sjl10e0VQgY)

I've added local state + setTimeout fix. I think it is a good solution for know considering code of Markdown preview component. 

Markdown preview uses styles which applies only after mounting components. That is a cause of flickering. And also this approach is not a react way. Refactoring of this part of code would take lots of time. This is why I decided to do a quick fix. After all maybe there was a reason for adding styles to a markdown after mounting.

### CODE REVIEW

**Comment by sosukesuzuki** [comment]
@max-buranbaev Thanks for your great PR:+1:. Your feature is work correctly in split editor.
However, not working in normal editor, like below:

**Comment by max-buranbaev** [comment]
@sosukesuzuki Thanks for the testing! I've fixed this issue as well.

jun-14-2018 15-48-36

**Comment by sosukesuzuki** [comment]
@max-buranbaev Umm, This pr is so buggy...
- Slow display when changing an note to be displayed.
- CodeEditor contents are not updated.

**Comment by max-buranbaev** [comment]
I've fixed the issue and also pulled all updates. 
Here are some demos. 
editing case
switching case

**Comment by infosisio** [comment]
@Rokt33r @sosukesuzuki I have personally tested this and it works really well.

**Comment by infosisio** [comment]
@Rokt33r @sosukesuzuki Have you tested this ? It's a major user experience improvement and it's really well made, no reason to delay putting it and blocking a good user benefit.

**Comment by sosukesuzuki** [comment]
@infosisio Thank you for reporting!
I think so too. I would like to review and merge within a few days:+1:

**Comment by infosisio** [comment]
@sosukesuzuki Any updates yet ? :)

**Comment by Rokt33r** [comment]
@max-buranbaev Could you fix the conflict? I'll merge it as soon as you fix it!

**Comment by max-buranbaev** [comment]
@sosukesuzuki Hey! I successfully merged it, so you can approve.

**Comment by infosisio** [comment]
@Rokt33r I have just tested this as well, works like a charm !!

**Comment by infosisio** [comment]
@Rokt33r @sosukesuzuki It should be ready for merge :)

**Pull request merged**
