### PR TITLE
Ability to stop auto update

### LINKED ISSUE #2140: Update should be optional
[Issuehunt badges](https://issuehunt.io/r/BoostIo/Boostnote/issues/2140)

# Feature Request
Hi,

I've used Boostnote for a while. Sometimes, the newer version is worst than the older one. So I make a request for the Boostnote's feature. Currently, updated version is automatically download and Boostnote will install the updated version when users accept OR after turn off and on Boostnote, which is compulsory. Could we change it to optional? User can choose to stay in the older version instead of installing the latest one.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $60.00)

- [boostio boostio](https://issuehunt.io/u/boostio) ($40.00)
- [chessmango chessmango](https://issuehunt.io/u/chessmango) ($20.00)
### Submitted pull Requests
- [#2617 Ability to stop auto update](https://issuehunt.io/r/BoostIO/Boostnote/pull/2617)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/BoostIo/Boostnote/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### PR DESCRIPTION
**Pull request by hsiehjack**
Fix #2140 

image

### CODE REVIEW

**Comment by daiyam** [comment]
@hsiehjack please use the existing config (`browser/main/lib/ConfigManager.js`)

**Comment by daiyam** [comment]
@hsiehjack Are you planning the make the change? It would be good to have your PR.

**Comment by hsiehjack** [comment]
@daiyam I made the changes already. Looks like there was a build fail. I will have to take a look at what happen.

**Comment by RonWalker22** [comment]
Any updates on this?

**Comment by hsiehjack** [comment]
Sorry for the long wait. This is ready for review.

**Comment by Flexo013** [comment]
@hsiehjack It looks like there are more conflicts. Could you resolve these, then we'll get this approved asap?

**Comment by hsiehjack** [comment]
@Flexo013 conflict fixed.

**Comment by Rokt33r** [comment]
I'll review this tomorrow!

**Comment by Rokt33r** [comment]
Sorry I've been insanely busy recently... I'll try to test it tonight or tomorrow. No more delaying I promise..! 🙏

**Comment by Rokt33r** [comment]
Confirmed that it's working well on macOS. I'm testing on WIndows now.

**Pull request merged**
