### PR TITLE
ALT key toggles the menu bar

### PR DESCRIPTION
**Pull request by klauscfhq**
Hi!
Now it's possible to have the menu bar hidden when launching the app, and only toggling it whenever you need it, just by pressing the `ALT` key!

🚀Tested both on **Windows 10 Pro** and **Linux Ubuntu 16.04**!

🔧It probably covers issues #281 & #169 

📷Here is a screenshot and an in action .gif running the windows build!

untitled-1

boostnote

### CODE REVIEW

**Comment by asmsuechan** [comment]
Hi @klauscfhq! Thanks for your PR. Could you remove the variable you deleted? https://travis-ci.org/BoostIO/Boostnote/jobs/212747642
Travis says `error  'showMenu' is assigned a value but never used  no-unused-vars`.

**Comment by asmsuechan** [comment]
Actually, I don't make sense this code @klauscfhq removed: `var showMenu = process.platform !== 'win32'`.
And I dug commits, I found this PR: https://github.com/BoostIO/Boostnote/pull/150. However, I don't have any ideas why he added this because it behaves only on mac thus it's useless. From these, I want to make a decision that it's his mistake to use ternary operator.

**Comment by klauscfhq** [comment]
Sorry for that 😄 Of course! Happy to contribute to the app! 🎉

**Comment by sota1235** [comment]
Thanks for contributing :)
We'll consider about this feature. Because the points like below.

- It is more smart design 🎨 
- But if the user don't know `alt` key feature, use can't never use menu bar features(export the note, confirm some information and etc...)

**Comment by gotenyama** [comment]
Hi any update on this ? I've asked a similar question on #537 seems like it is waiting for PR to be merged by collaborators.

**Comment by jasondavis** [comment]
This is a common feature among Windows apps to use the `ALT` key to toggle toolbar so I would say it's a good PR

**Comment by klauscfhq** [comment]
@gotenyama @jasondavis You can add the feature to your local build just by switching the `autoHideMenuBar: showMenu`  property to `autoHideMenuBar: true`, which is located inside the `resources/app/lib/main-window.js` file.
It can be a temporary fix, until a better implementation is achieved, though you would still have to repeat it after an app update! 
Hope it helps 😄

**Pull request closed without merging**
