### PR TITLE
refs #239 Fixes a bug which cannot open finder with using HotKey

### PR DESCRIPTION
**Pull request by asmsuechan**
Hi, I tried to fix however nothing thinking to fix it.

### CODE REVIEW

**Comment by sota1235** [comment]
Thank you!!!! I'll check it!!!

**Comment by sota1235** [comment]
I confirm bug is fixed. I'll release this code tonight. Thank you!!

**Comment by sota1235** [comment]
Related #239

**Comment by asmsuechan** [comment]
Oops, should we add lib/finder-app.js to .eslintignore?

**Comment by sota1235** [comment]
I fixed by ignoring the line.
https://github.com/BoostIO/Boostnote/commit/ad4e50d54241637c288ba8eac6cc0fdf2349514b

So, if you'll get same problem, please use ignore the code with inline comments!
http://eslint.org/docs/user-guide/configuring#disabling-rules-with-inline-comments

**Comment by asmsuechan** [comment]
Wow! I didn't know. Thanks for this information!

**Pull request merged**
