### PR TITLE
Fullscreen shortcut for non macOS

### PR DESCRIPTION
**Pull request by yougotwill**
Feature added for #1711 

Fullscreen on macOS remains ```Cmd+Ctrl+F```
Fullscreen on Linux and Windows is ```F11```

### CODE REVIEW

**Comment by romainwn** [comment]
Does it run on your windows/Linux ?

The `window` submenu is only displayed on macOs as far as I know, and the toggleFullScreen: is [specific to macOs](https://developer.apple.com/documentation/appkit/nswindow/1419527-togglefullscreen?language=objc)

Maybe you should try to place it in the View submenu, and use the [setFullScreen method](https://electronjs.org/docs/api/browser-window#winsetfullscreenflag) instead 😄

**Comment by yougotwill** [comment]
Good to know thanks, will get right on that :)

**Comment by yougotwill** [comment]
Tested on windows and it works fine.

**Comment by romainwn** [comment]
Also tested on Windows and it works fine too.
Just tested it on macOs, when I click on the item it does toggle fullscreen, but shortcut `cmd + ctrl + F` doesn't toggle and instead focus the `Search` input.

Maybe we should keep macOs as it is, and only make your changes for the non macOs platforms ?
What do you think @Rokt33r ?

**Comment by Rokt33r** [comment]
I think we should add another `window` menu for linux and windows.

**Comment by yougotwill** [comment]
@Rokt33r Sure thing will get on it this evening 👍

**Comment by yougotwill** [comment]
@romainwn @Rokt33r I changed the logic to be either of the fullscreen methods depending on the platform. Having said that @romainwn that error you mentioned about it focusing on the ```search``` input is on master as well. :/

**Comment by yougotwill** [comment]
Ok so that change doesn't work on windows. So I have reverted the commit and will leave it until we find out if the issue comes from the master branch.

**Comment by Rokt33r** [comment]
@romainwn ping.

**Comment by romainwn** [comment]
oh yup sorry for the delay. I'll try to make a PR by this week end, quite busy for the next two days !

**Comment by Rokt33r** [comment]
I'll wait for it gladly.

**Comment by yougotwill** [comment]
I'd like to suggest we change the `focus on search bar` shortcut to `Cmd/Ctrl + L` which is a more standard shortcut that I have seen in various apps for focusing the main input/search box in an app. (i.e. Chrome, Spotify)

Also @romainwn are you referring to this issue https://github.com/BoostIO/Boostnote/issues/1803 specifically a shortcut for the editor fullscreen option?

**Comment by romainwn** [comment]
Oh didn't notice this issue.
Actually I was referring to #1711, the one you were trying to implement which is toggle fullscreen for non-macOs. 

For the FullScreen shortcut I was thinking to use `F11` for windows and Linux, and keep `Cmd + Ctrl + F` for macOs

**Comment by yougotwill** [comment]
This branch does exactly that :) All we need to do is change the `focus on search bar` to a different keyboard shortcut so that it doesn't interfere with the fullscreen shortcut and once we confirm that everything works correctly again then we are sorted 👍

**Comment by yougotwill** [comment]
So I have tested by changing the `top:focus-search` as mentioned above. The fullscreen shortcut then works perfectly. @Rokt33r Should I put these changes in a separate pr and leave this one alone for now?

**Comment by Rokt33r** [comment]
@yougotwill I don't think so. Just update this branch. And I agree changing shortcut key for `top:focus-search `.

**Comment by yougotwill** [comment]
@Rokt33r Changes done, and I have tested on windows and everything works correctly 👍

**Comment by Rokt33r** [comment]
LGTM

**Pull request merged**
