### PR TITLE
Color update

### PR DESCRIPTION
**Pull request by ytk141**
- Update Dark Theme Color
- Hidden zoom panel
- Change Note Detail Icon Color

ver a

### CODE REVIEW

**Comment by kazup01** [comment]
Hi @ytk141 , thanks for contribution! Please check the below.

- The Star button in SideNavFilter is expanding when active, so please improve it.
dec-11-0029 17-23-01

- There is a weird margin when the Progress bar is active, so please fix it.
screen shot 0029-12-11 at 5 37 51 pm

**Comment by ytk141** [comment]
@kazup01 Fixed bugs adove!

**Comment by kazup01** [comment]
Cool!

**Comment by ytk141** [comment]
@kazup01 Updated some styles. plz check it :)

**Comment by kazup01** [comment]
Merged! Thanks @ytk141 <3

**Comment by kazup01** [comment]
I will fix CI error soon.

**Pull request merged**
