### PR TITLE
tag enhancements

### PR DESCRIPTION
**Pull request by daiyam**
This change add 2 new options:
- `showTagsAlphabetically`: show tags of a note in alphabetical order.
- `enableLiveNoteCounts`: enable live count of notes in the Side Bar. (tags without any related notes have no displayed count)

### CODE REVIEW

**Comment by modmod24** [comment]
hi, would it make sense to sort the tags only once when they are created (and store in this order in file), instead of every time the  note is displayed?

sorry if this suggestion doesn't make sense. I am not exactly sure what your changes does.

**Comment by daiyam** [comment]
@modmod24 no, it does make sense. But what about the existing tags?

Maybe the option `saveTagsAlphabetically` should be added or should replace `showTagsAlphabetically `.
That option is shown with a warning that by selecting it, it would sort the existing tags.
There might be a performance issue since we will have to re-save all the notes; same issue when we will be able to rename a tag...

**Comment by modmod24** [comment]
@daiyam I was thinking about ordering only when saving tags, to prevent frequently ordering what's already in order. existing order would remain until new tag added.

**Comment by modmod24** [comment]
yes, of course. thanks.

**Comment by Rokt33r** [comment]
> enableLiveNoteCounts: enable live count of notes in the Side Bar. (tags without any related notes have no displayed count)

Could you tell me more what it is?

**Comment by daiyam** [comment]
@Rokt33r here some screenshots to explain it better:

When `enableLiveNoteCounts` is **off** (by default):
screenshot

When `enableLiveNoteCounts` is **on**:
screenshot

The count on `bug` isn't shown because there is no notes with `feature` **and** `bug` tags.
The count on `table` is `1` instead of `4` because only one note has both `feature` **and** `table` tags.

**Comment by Rokt33r** [comment]
I confirmed it works fine. Thanks for being late!

**Pull request merged**
