### PR TITLE
might fixes #1786 --> export attachments for markdown notes

### LINKED ISSUE #1786: [Feature Request] Markdown Export with Images
Exporting to markdown will not export the images. 
There should be an option to export in the **assets** subfolder.

current export image:
```
![0.04i5dwoqj2x6](\:storage\0.04i5dwoqj2x6.png)
```

should be:
```
![image1](\assets\image1.png)
```

### PR DESCRIPTION
**Pull request by ehhc**

### CODE REVIEW

**Comment by ZeroX-DG** [comment]
LGTM :+1:

**Comment by Rokt33r** [comment]
@ehhc Could you tell me what does this PR? I couldn't understand which problem is fixed by this PR.

**Comment by ehhc** [comment]
If you export a note that contained images as a markdown file, the attachments/images should be exported as well an the links to these files should be valid (instead of `:storage/...`). If you open the exported note in a markdown preview program you should be able to view the content inclusive the rendered images/files.

**Comment by ehhc** [comment]
see https://github.com/BoostIO/Boostnote/issues/1786

**Comment by Rokt33r** [comment]
@ehhc I see the point! It looks good to me!

**Pull request merged**
