### PR TITLE
Add setting for adding additional styles to preview panel

### PR DESCRIPTION
**Pull request by kschiffer**
As raised in #1913, I have added an option to add additional CSS to the markdown preview iframe, enabling fine-tuning on how the preview looks:
image

### CODE REVIEW

**Comment by Rokt33r** [comment]
Outstanding!! 🎉

**Comment by bimlas** [comment]
I think this is related to https://issuehunt.io/repos/53266139/issues/184 thus @kschiffer could get the reward.

**Comment by kschiffer** [comment]
@bimlas Oh nice :)

**Comment by kschiffer** [comment]
I have fixed the linting issues that made CI fail. Let me know if you need anything else.

**Comment by Splitix** [comment]
Nice work @kschiffer. I also added a reward to #184. Hope this goes through. Something I'm really looking forward to.

**Comment by sosukesuzuki** [comment]
Sorry, this feature was implemented by #1996.
I'll close this pr:bow:

**Pull request closed without merging**
