### PR TITLE
add tag autocomplete

### PR DESCRIPTION
**Pull request by daiyam**
This change adds tag autocomplete #192

### CODE REVIEW

**Comment by ZeroX-DG** [comment]
Hey @daiyam can you filter tags that has already been added ? I think it will be better.

**Comment by daiyam** [comment]
@ZeroX-DG good idea! It's done.

**Comment by ZeroX-DG** [comment]
Nice! LGTM

**Comment by daiyam** [comment]
@Rokt33r I removed `awesomplete` and replaced it with [`react-autosuggest`](https://github.com/moroshko/react-autosuggest).

**Comment by Rokt33r** [comment]
@daiyam LGTM. Btw, it doesn't work on snippet notes. Could you fix it too?

**Comment by daiyam** [comment]
@Rokt33r I've submit the pull request #2400 to fix it.

**Comment by kazup01** [comment]
Hi @daiyam, I featured your contribution on release blog! 
https://medium.com/boostnote/boostnote-v0-11-10-release-on-halloween-9bbe6d488fe8

**Comment by ehhc** [comment]
@daiyam i just wanted to say that i like your feature. It's pretty cool :)

**Comment by daiyam** [comment]
@ehhc thx

**Comment by arcturus140** [comment]
yeah, best feature ever! :+1:  I was longing for this from the first time I've used BN. So many redundant tags due to inconsistent letter case, plural / singular, synonyms, etc. 

I had a script before to rename all tags to clean it all up.

**Pull request merged**
