### PR TITLE
Fix note title

### PR DESCRIPTION
**Pull request by asmsuechan**
I change to show underscores(_) in title

1825ed2fb5d8232730022ffca935d58b

### CODE REVIEW

**Comment by sota1235** [comment]
I think it is too hard to read. So I added unit test.
https://github.com/asmsuechan/Boostnote/pull/4

Please confirm it.

**Comment by asmsuechan** [comment]
I think so. I assume that PR is better.

**Comment by sota1235** [comment]
@asmsuechan plz resolve conflicts

**Comment by asmsuechan** [comment]
Done.

**Comment by kazup01** [comment]
Merged. Thank you for your contribution @asmsuechan !

**Pull request merged**
