### PR TITLE
Sean/improve english

### PR DESCRIPTION
**Pull request by mrseanbaines**
image

### CODE REVIEW

**Comment by kazup01** [comment]
Thanks for your contribution @mrseanbaines ! Could you fix conflict?  #935  #936

**Comment by kazup01** [comment]
Merged

**Comment by kazup01** [comment]
I think that these PRs should be put together because these cause conflict. #935 #936 
Could you fix these conflict? Thanks for your help!

**Comment by kazup01** [comment]
I closed #935 #936, it would be very helpful if you send me a new PR. Thanks.

**Comment by mrseanbaines** [comment]
@kazup01 #940

**Pull request merged**
