### PR TITLE
Use the correct handler for closing the modal.

### LINKED ISSUE #967: Uncaught TypeError: _this5.handleCloseButtonClick is not a function
# context
The init modal cannot escape by clicking the esc button and pushing the esc key.
image

# how to reproduce
1. clone Boostnote and run `yarn && yarn run dev-start`
2. initialize Boostnote to delete `localStorage.storages` by hand from `Application` in Electron if you've already had Boostnote development environment
3. reload Boostnote
4. try to escape from the initial modal

### PR DESCRIPTION
**Pull request by Samatar26**
Fixes #967
Used the correct handler for closing the modal. I don't think I'l be able to demonstrate this using pictures so maybe try running it locally, sorry.

### CODE REVIEW

**Comment by kazup01** [comment]
Merged. Thanks for your contribution @Samatar26 !

**Comment by Samatar26** [comment]
@kazup01 どう致しまして,  頑張りましょう!

**Comment by kazup01** [comment]
@Samatar26 ありがとうございます👍

**Comment by kazup01** [comment]
This improving feature has just released at v0.8.16! Thanks!
https://github.com/BoostIO/Boostnote/pull/1027

**Pull request merged**
