### PR TITLE
lint before commit

### PR DESCRIPTION
**Pull request by daiyam**
This change is running the `lint` command before a commit.

### CODE REVIEW

**Comment by jacobherrington** [comment]
I personally think forcing lint on commits is a bit heavy handed - our CI already runs lint so I don't think it's totally necessary.

**Comment by ZeroX-DG** [comment]
I think with pre-commit hook we can detect the problem right away without waiting for the CI to fail and prevent some unnecessary commit like "fixed lint" :smile:

**Comment by ZeroX-DG** [comment]
LGTM but can you discard `yarn.lock`? Also, I think running test in the pre-commit hook is a bit heavy for small changes (There's still some chance that small changes can cause failed tests, but I think leaving it to the CI is the best). @daiyam

**Comment by daiyam** [comment]
@ZeroX-DG I agree with you since the tests are heavy.

**Comment by Rokt33r** [comment]
@ZeroX-DG @daiyam I think tests should be executed before pushing. So how do you think add pre-push hook for testing?

**Pull request merged**
