### PR TITLE
Keyboard nav

### PR DESCRIPTION
**Pull request by justin-calleja**
This PR replaces #542.

I have applied the commits on the current master and resolved conflicts. Also, the commits are split into smaller commits.

Keyboard navigation is still not implemented in Finder. This is already a big list of changes. Maybe it's best to open a separate issue for the Finder.

### CODE REVIEW

**Comment by kazup01** [comment]
There are many conflicts. I'm sorry, could you fix these?
This feature is great. Thank you for your contribution @justin-calleja !

**Comment by justin-calleja** [comment]
@kazup01 there will always be many conflicts if I re-do the work and it's never merged in.

The first time, there was an issue with the commits containing too much code. Then the project moved forward and I had to not only split the commits but refactor.

Once that was done, no feedback was given and the project evolved again breaking this PR.

What's going to change this time if I re-do the work again?

**Comment by kazup01** [comment]
Hi @justin-calleja , thank you for your reply.
I understand your opinion but it is too huge so difficult to review.
Could you split this pull request into several? 

We think that this feature is awesome. Thank you again.

**Comment by justin-calleja** [comment]
@kazup01 Ok, I thought the problem was that the commits were too big. I made them smaller and included them in one PR as they are related to the same feature the PR addresses.

Can you please let me know sooner? As in, I had already submitted this PR for review and @asmsuechan was suppose to look at it and come back with feedback. Now there are probably many merge conflicts to resolve (apart from me having to get familiar with the code again).

When I have some time, I'll look into splitting up in smaller PRs - however, I will only issue one PR at a time. Once one is merged, I'll look into making the next PR.

I hope you understand I cannot keep re-writing this code.

Thanks.

**Comment by kazup01** [comment]
Hi @justin-calleja , thanks for your kindly support. I understand your opinion.
If you want to reopen it, could you fix the conflicts?
Actually asmsuechan is leaving the maintainer, so another maintainer will review that.

Thanks.

**Pull request closed without merging**
