### PR TITLE
New snippet tabbar

### PR DESCRIPTION
**Pull request by nlopin**
This is the first part of new scrollable tabbar in snippet notes. 
Demo: http://g.recordit.co/KWMEk1OPKX.gif

What's left:
- [x] scroll controls should appear after there are enough tabs for scrolling
- [x] allow to scroll tabs with touchpad
- [x] process delete tabs correctly
- [x] refactor formulas

Related issue #1279

### CODE REVIEW

**Comment by pfftdammitchris** [comment]
Looks great, I like it. What about vertical lines to separate each note?

**Comment by nlopin** [comment]
Sorry for delay, guys. It's coming

**Comment by nlopin** [comment]
@Rokt33r I've finished this. I had to add manual animation for scroll, because current version of Chrome doesn't have smooth scroll on `scrollIntoView` function. Feel free to ask any questions.

I'm not sure what happened with test, I've changed nothing in move folder part of the app.

**Comment by nlopin** [comment]
@Rokt33r @kazup01 Could you please review the code?

**Comment by kazup01** [comment]
Hi @nlopin , thank you for your support 😄 Please wait a while.

**Pull request merged**
