### PR TITLE
Add tag link handling with :tag:#tag syntax

### PR DESCRIPTION
**Pull request by AWolf81**
## Description
I've added the tag links by using `:tag:#tag` link syntax. 
It's working but not ready for merge because I'd like to wait for React upgrade because I'm using hashHistory directly. This will be changed later to `dispatch(push(...))`

## Issue fixed

#1683

## Type of changes

- :white_circle: Bug fix (Change that fixed an issue)
- :white_circle: Breaking change (Change that can cause existing functionality to change)
- :white_circle: Improvement (Change that improves the code. Maybe performance or development improvement)
- :radio_button: Feature (Change that adds new functionality)
- :white_circle: Documentation change (Change that modifies documentation. Maybe typo fixes)

## Checklist:

- :radio_button: My code follows [the project code style](docs/code_style.md)
- :white_circle: I have written test for my code and it has been tested
- :white_circle: All existing tests have been passed
- :radio_button: I have attached a screenshot/video to visualize my change if possible --> see issue

## Note
The tag links are not handled in editor just in `MarkdownPreview` and I think we should open a new issue for this as I think the other link types (:line) are also not handled - or is line & tag handling only required in preview? I think they should be handled as there is a tooltip indicating how to click but the click is not working.

### CODE REVIEW

**Comment by AWolf81** [comment]
@ZeroX-DG sure, I've resolved the conflict and checked the feature.

I'll open an issue (if it's not already in the issues) for the Crtl+Link click that's not working for tag and line links as mentioned in my note above.

For the failing Travis CI I think that's caused by linting errors. I'll create a separate PR for it as that's more work do to (e.g. check prettier with standard.js usage).

**Comment by Rokt33r** [comment]
@AWolf81 @ZeroX-DG I don't think we need to keep `#`. `:tag:tag` should be enough. How do you think?

**Comment by ZeroX-DG** [comment]
That could be a good idea. Keep the consistency with other type of links like `:note:` or `:line:`. I'm OK with either way so @AWolf81 what do you think about this?

**Comment by AWolf81** [comment]
I would keep it with the hash as it's easier to remember and I think it would be confusing to users. As the tag is always displayed with the # in front.
The consistency would be better and it's an easy change - just removing the hash from the Regex.

Maybe if there would be a context menu to add tag links we could do it with-out #. But we should create an issue for this and discuss it there e.g. right click on tag shows `Insert link to tag`.

**Comment by Rokt33r** [comment]
@AWolf81 

I think prefixing `:tag:` is already enough to prevent the confusing. So yeah, I want to keep consistency so users can expect same behavior of other internal links. So please fix it. :pray: 

>  Maybe if there would be a context menu to add tag links we could do it with-out #. But we should create an issue for this and discuss it there e.g. right click on tag shows Insert link to tag.

Sounds good to me but should be better to presented in a separated PR.

**Comment by AWolf81** [comment]
@Rokt33r sure. I've fixed it. 👍 

For the context menu I'll create an issue and start working on it later today.

**Pull request merged**
