### PR TITLE
Fix a Bug when using the Finder Window with markdown Notes

### PR DESCRIPTION
**Pull request by asmsuechan**
Hi, this PR is for handling https://github.com/BoostIO/Boostnote/issues/246. It occurs on blur. Thus I removed blur handler.

### CODE REVIEW

**Comment by kazup01** [comment]
Wow, Very early!
You are superman! Thank you for your everday supports!!!! We'll check it!

**Comment by asmsuechan** [comment]
Umm, this PR fixes the bug but I feel it seems to decrease usability for now...

**Comment by asmsuechan** [comment]
I recognized an issue that click event becomes invalid when the `MarkdownPreview` area is focused in finder. Perhaps, the cause is that `iframe` in `MarkdownPreview` grabs the events.

**Comment by sota1235** [comment]
Thank you for fixing. LGTM!

**Pull request merged**
