### PR TITLE
Fix long code lines that do not wrap in exports

### PR DESCRIPTION
**Pull request by kotlarz**
## Description

Surprising easy fix. Break the line for code snippets so that the snippets do not get cut-off when exporting to HTML and PDF (via. HTML).

##### Before:
Selection_439

##### After:
Selection_440

##### Before:
Selection_441

##### After:
Selection_442

## Issue fixed
#3051 

## Type of changes

- :radio_button: Bug fix (Change that fixed an issue)
- :white_circle: Breaking change (Change that can cause existing functionality to change)
- :white_circle: Improvement (Change that improves the code. Maybe performance or development improvement)
- :white_circle: Feature (Change that adds new functionality)
- :white_circle: Documentation change (Change that modifies documentation. Maybe typo fixes)

## Checklist:

- :radio_button: My code follows [the project code style](docs/code_style.md)
- :white_circle: I have written test for my code and it has been tested
- :radio_button: All existing tests have been passed
- :radio_button: I have attached a screenshot/video to visualize my change if possible

### CODE REVIEW

**Comment by Flexo013** [comment]
This is a great improvement. Could you also make the line number jump to the right line after the previous line wrapped one or more times?

**Comment by kotlarz** [comment]
@Flexo013 Sorry about the late reply.
I'll take a look at it sometime today 👍

**Comment by Flexo013** [comment]
@kotlarz I see you pushed new commits. Could you update the screenshots of the PR description so that they match with the latest version?

**Comment by ZeroX-DG** [comment]
ping @kotlarz can you fix the conflict please?

**Comment by kotlarz** [comment]
@ZeroX-DG done.

@Flexo013 I took a look and it's a bit more work than I initially thought. It comes down to how the preview component grid is setup. MarkdownPreview renders the gutter/content differently than CodeEditor (which does it correctly).

I'm not sure, but I think MarkdownPreview kinda uses CodeMirror incorrectly as the preview and gutters are instead created via. the markdown renderer (`/browser-lib/markdown.js`):
Selection_472

I read through the CodeMirror documentation and there's a `lineWrapping` option for the editor, and it works 100% for the CodeEditor. But the component grid layout is different, as seen in the picture below.
Selection_473

I think the MarkdownPreview grid need some rework, unless there's a simple fix I'm not seeing.

**Comment by ZeroX-DG** [comment]
@kotlarz yes I think there's no easy way to fix this. Can you rework on the code rendering for markdown preview? Do you think it's better to restructure the code preview html structure or use a external lib like https://prismjs.com/ or https://highlightjs.org/

**Comment by kotlarz** [comment]
@ZeroX-DG Yeah I can rework it once I have some free time. Might be better to use an external library instead of creating your own solution (why re-invent the wheel?). I'll take a look if it's worth restructuring to use a lib vs. fix the preview component.

**Comment by ZeroX-DG** [comment]
@kotlarz have you found a way to solve this yet?

**Comment by ZeroX-DG** [comment]
I'll take over this PR on Wednesday. If you interested in solving this yourself, feel free to re-open the PR

**Pull request closed without merging**
