### PR TITLE
Strange url-handling reverted + tests modified so that they might fin…

### LINKED ISSUE #2834: can not preview local pics in 0.11.13
# Current behavior
Can not show the pics(jpg,bmp,gif,svg) by markdown which is OK in previous version. But images by website is OK.

new bitmap image

``
Does not show image.

``
Does show image.

# Expected behavior
Can show local images.

# Steps to reproduce
Drag local pics to notes.

# Environment
- Version : 0.11.13
- OS Version and name : Win10 64bit professional

### PR DESCRIPTION
**Pull request by ehhc**
Strange url-handling reverted + tests modified so that they might fin…d that issue in the future + test modified so that they both contain tests for posix and windows path separator -> fixes #2834

### CODE REVIEW

**Comment by ehhc** [comment]
the idea of the changes in the tests was that they should test both for posix and windows systems.. obviously that still dosen't work correct (they are green at my maschine since the fist commti -.-)

**Comment by daiyam** [comment]
The problem with the regex `'/?' + STORAGE_FOLDER_PLACEHOLDER + '.*?"'` is the usage of the terminator `"`.

For an image, it generates `"`, so the path is correctly found.
For a gallery, it generates:
```
<div class="gallery">
path1
path2
path3
</div>
```
In that case, the paths won't be found.

**Comment by daiyam** [comment]
@ehhc, here the fixed regex:
```
function fixLocalURLS (renderedHTML, storagePath) {
  /*
    A :storage reference is like `:storage/3b6f8bd6-4edd-4b15-96e0-eadc4475b564/f939b2c3.jpg`.

    - `STORAGE_FOLDER_PLACEHOLDER` will match `:storage`
    - `(?:(?:\\\/|%5C)[-.\\w]+)+` will match `/3b6f8bd6-4edd-4b15-96e0-eadc4475b564/f939b2c3.jpg`
    - `(?:\\\/|%5C)[-.\\w]+` will either match `/3b6f8bd6-4edd-4b15-96e0-eadc4475b564` or `/f939b2c3.jpg`
    - `(?:\\\/|%5C)` match the path seperator. `\\\/` for posix systems and `%5C` for windows.
  */
  return renderedHTML.replace(new RegExp('/?' + STORAGE_FOLDER_PLACEHOLDER + '(?:(?:\\\/|%5C)[-.\\w]+)+', 'g'), function (match) {
    var encodedPathSeparators = new RegExp(mdurl.encode(path.win32.sep) + '|' + mdurl.encode(path.posix.sep), 'g')
    return match.replace(encodedPathSeparators, path.sep).replace(new RegExp('/?' + STORAGE_FOLDER_PLACEHOLDER, 'g'), 'file:///' + path.join(storagePath, DESTINATION_FOLDER))
  })
}
```

I've forgot that the `\w` doesn't include the `-`...

Anyway, thanks for the updated tests.

**Comment by Rokt33r** [comment]
@daiyam @ehhc Is this pr ready? If so, I'll review it today.

**Comment by ehhc** [comment]
@daiyam can you merge my PR with your fixed regex? So that we have a working attachmentMangement with proper tests again? + can you include tests for your image gallery?? 

@Rokt33r the PR would fix the attachment problem but would break the gallery... Unfortunately i don't have time to fix both.. but i think @daiyam will? (hopefully..?)

**Comment by daiyam** [comment]
@Rokt33r go ahead to merge this PR to fix the urgent bug.
I will do another PR with the regex fixed and some tests for the gallery.

**Comment by Rokt33r** [comment]
I confirmed that it works on Windows. Btw, I've tried this on macOS and it seems that both v0.11.13 and this pr don't work on macOS.(This should be other problem I think)

@ehhc Do you think you can fix this too?

@ZeroX-DG Could you check that dragging an image to editor works on Linux?

**Comment by ZeroX-DG** [comment]
Dragging the image into editor works fine for me on Linux both the current version and this PR. Seem that Linux is not affected by this bug.

**Comment by Rokt33r** [comment]
> are the jest-Tests (yarn jest) working on Mac?
@ehhc Yeah it works fine.

screen shot 2019-01-29 at 17 42 41

**Comment by ehhc** [comment]
@Rokt33r then i have no idea whats wrong on mac.. sorry :(

**Comment by daiyam** [comment]
@Rokt33r I already have the PR #2642 to fix the issue you are getting 😉

**Comment by daiyam** [comment]
@ehhc @Rokt33r I've made the PR #2848 to fix the regex

**Pull request merged**
