### PR TITLE
Add option to disable the automiatic deletion of un-referenced attach…

### LINKED ISSUE #3203: Files, Images get deleted automatically after dragging them on to boostnote interface.
# Current behavior

 
Let us know what is currently happening.
When dragging and dropping the files and images, it gets deleted automatically after some time. It does not happen always, but it happens say 30% of the times. The file cannot even be seen in recycle bin. For some reason, I am never able to put files with "psd" extension (photoshop files ) on boostnote.  It does not even accept it. The issue is very similar to this link: https://github.com/BoostIO/Boostnote/issues/1788 .  Since it says it's solved, I am submitting the issue again. 
 

# Expected behavior

 
The file should not get deleted. It should remain in the folder like any other files. 
 
# Steps to reproduce

1. Select any image
2. Drag and drop on the notes
3. Sometimes it gets saved, however many times the image gets automatically removed either instantly or after some time. I cannot even find it in the recycle bin. It just vanishes to nowhere. 

# Environment

- Boostnote Version : 0.12.1
- OS Version and name : Mac

### PR DESCRIPTION
**Pull request by ehhc**
…ments -> might fix #3203

@Rokt33r  what do you think about this?

### CODE REVIEW

**Comment by ZeroX-DG** [comment]
@ehhc , in this case, do the user have anyway to know how many unused attachments that he/she has? And is there a way for the users to easily remove all of them to save space?

**Comment by ehhc** [comment]
hi @ZeroX-DG,
no there is no way to know how many unused attachments exist. furthermore there is no (easy) way to delete them.
I don't have the time (and don't want to) implement that..
If they don't want attachments to be deleted, they have to do it manually in my opinion..

**Comment by ZeroX-DG** [comment]
I'll try to find a way to get unused attachments and make a button to clean those things up and submit a PR to your PR.

**Comment by ehhc** [comment]
@ZeroX-DG @Rokt33r i've merged the changes into my PR

**Comment by ZeroX-DG** [comment]
@Rokt33r I mark this as `need more review` because I contributed to this PR too so I can't approve my own code :smile:

**Comment by Rokt33r** [comment]
@ehhc @ZeroX-DG This pr hasn't passed in CI yet...!

**Comment by ZeroX-DG** [comment]
@Rokt33r I missed a small detail and have submitted a PR to fix this. We have to wait for @ehhc to merge it. Sorry for the inconvenience
https://github.com/ehhc/Boostnote/pull/2

**Comment by ehhc** [comment]
@ZeroX-DG @Rokt33r done

**Pull request merged**
