### PR TITLE
Added Turkish translation

### PR DESCRIPTION
**Pull request by onurpalaz**
Just added JSON file under the 'locales' folder for the Turkish translation. Some translations might not perfectly fit into the app's daily usage. As soon as i test the translations with the real app, i will fix the errors and update the JSON file. Cheers...

### CODE REVIEW

**Comment by kazup01** [comment]
Thanks @onurpalaz for your contribution.
Is there anyone who can review it in Turkish?

**Comment by berkandirim** [comment]
I've reviewed it and it's good to go.

**Comment by Rokt33r** [comment]
I've fixed this. 😄

**Comment by kazup01** [comment]
Thanks @onurpalaz and @berkandirim 🎉

**Pull request merged**
