### PR TITLE
Add translation to Portuguese from Portugal

### PR DESCRIPTION
**Pull request by FabioRosado**
Hello!
This is my first time contributing to Boosnote, I am not sure if this is the best/right way to contribute with a translation to the project, but I have noticed that Boosnote has a translation for Portuguese from Brazil, since some terms are different in the Portuguese from Portugal I have decided to work on a full translation to it.

I hope this looks good, let me know if I should change something 👍 

Thank you for your time

### CODE REVIEW

**Comment by ZeroX-DG** [comment]
Hey @FabioRosado , Welcome to Boostnote! Thank you for your contribution, but do you know someone else can review your change? Because I'm not sure if there's anyone here who speaks Portugal

**Comment by FabioRosado** [comment]
Hello @ZeroX-DG  Thank you for the quick reply. I don't know anyone that could review this PR, most people I know only speak English haha

**Comment by Rokt33r** [comment]
I'm going to merge this in the next week if there is no reviewer!

**Comment by FabioRosado** [comment]
Hello @jangtsekiang  thanks for this review, some things I have missed and your suggestions where bang on (I guess living abroad for so long made me unsure in some cases haha) I have decided to opt to use "A Equipa do Boostnote" instead of "de" because it sounded a bit better.

Much appreciated for your help @jangtsekiang  😄 👍

**Comment by Rokt33r** [comment]
@jangtsekiang Do the changes look fine?

**Comment by FabioRosado** [comment]
I was thinking about this PR today, do we need to add something to the languages file? Currently there is only one Portuguese which defaults to PT-BR, should this version of Portuguese file be added as a separate language (in some places you can choose PT-BR or PT-PT kind of like the British English and US English)?  Or the file will be chosen depending on the system locale?

**Comment by jangtsekiang** [comment]
@FabioRosado you are right, lol. There actually already exist two language files, PT-PT and PT-BR but only one option in the GUI.

**Comment by arcturus140** [comment]
@FabioRosado I started a PR to your branch.

**Comment by FabioRosado** [comment]
@arcturus140 I was going to work on this today after work, thanks a lot for being so quick and add this 😄 👍  I have merged your PR into this branch so now everything should work fine 😄

**Comment by Rokt33r** [comment]
Awesome work! @FabioRosado Is it fine to merge now?

**Comment by FabioRosado** [comment]
@Rokt33r  Apologies I should have said yesterday, yeah everything looks good now thank you 😄 👍

**Pull request merged**
