### PR TITLE
Change the :storage* links to attachments

### PR DESCRIPTION
**Pull request by CedricHerzog**
## Description
The HTML export creates a folder "attachements" with all the files linked to the Boostnote .md file.
However the links created in the .html file do not point to this "attachements" folder and keep using ":storage/.." representation as used in the Boostnote .md file.

This request changes the links in the HTML export from ```:storage/12323-2133123-21312323-123323/file.extension``` to ```attachments/file.extension```.

Works on windows if folders separated by "%".

I uses a simple regex ```:storage(\/|%)[a-zA-Z0-9-]*```and replaces it by "attachements".

## Type of changes

- :white_circle: Bug fix (Change that fixed an issue)
- :white_circle: Breaking change (Change that can cause existing functionality to change)
- :white_circle: Improvement (Change that improves the code. Maybe performance or development improvement)
- 🔘  Feature (Change that adds new functionality)
- :white_circle: Documentation change (Change that modifies documentation. Maybe typo fixes)

## Checklist:

- 🔘  My code follows [the project code style](docs/code_style.md)
- :white_circle: I have written test for my code and it has been tested
- 🔘  All existing tests have been passed
- 🔘  I have attached a screenshot/video to visualize my change if possible

Screenshot 2019-03-20 at 00 07 19

### CODE REVIEW

**Comment by ZeroX-DG** [comment]
@CedricHerzog can you fix the conflict?

**Comment by dredav** [comment]
Duplicate of fix #2901 or #2897?

**Comment by CedricHerzog** [comment]
> 
> 
> Duplicate of fix #2901 or #2897?

As I understand the goal of these fixes was to fix the creation of the "attachments" folder during the export. My fix's purpose is to set the right paths to these folder in the HTML file.

**Comment by CedricHerzog** [comment]
Any news?

**Comment by incredibleweirdo** [comment]
> > Duplicate of fix #2901 or #2897?
> 
> As I understand the goal of these fixes was to fix the creation of the "attachments" folder during the export. My fix's purpose is to set the right paths to these folder in the HTML file.

@CedricHerzog  This is a duplicate of #2897 to be sure. It's implemented differently, yes, but they are addressing the same issue.

**Comment by noklam** [comment]
any update on this? this broken link is very annoying when I want to export a few folder of markdown..

**Comment by noklam** [comment]
> any update on this? this broken link is very annoying when I want to export a few folder of markdown.. Would appreciate if this can be fixed.

As a quick fix to export markdown for other usage, I use this script to copy the storage and convert the notes to markdown.

https://gist.github.com/noklam/08d7afd25dd6e15b0208c3b782ebebfc

**Comment by Flexo013** [comment]
The main reviewers are currently very busy so it might take some time for PRs to be reviewed.

**Comment by CedricHerzog** [comment]
> 
> 
> The main reviewers are currently very busy so it might take some time for PRs to be reviewed.

Some time OK, but 8 months is a bit long.
Please close the pull request if it really is a duplicate as @incredibleweirdo explained.

**Comment by ZeroX-DG** [comment]
Close because it's a duplicate of https://github.com/BoostIO/Boostnote/pull/2897

**Pull request closed without merging**
