### PR TITLE
Fixed lock button behavior and display

### LINKED ISSUE #2121: Locking/Unlocking state bug
# Current behavior
The state of the lock/unlock icon can get stuck in an incorrect state

image

# Expected behavior
Either the icon display is reset with the locking state, or the locking state stays consistent with what the icon indicates.  Personally, I would prefer if the locked state stayed on if it was selected, that is, when leaving the split pane view, it would return to the edit view if it was locked

# Steps to reproduce

 1. Click in the boostnote field to edit
 2. Click lock
 3. Enable dual pane view (I did so with the hotkey)
 4. Disable dual pane view (I did so with the hotkey)
     - Automatically goes back to rendered view (not the edit view)
 5. Icon shows it is locked, when it is not.
 6. Repeat to switch the icon back to correct

# Environment

- Version : 0.11.6
- OS Version and name : Windows10

### PR DESCRIPTION
**Pull request by miguelalexbt**
## Description
Fixed the bug reported in #2121. Now, the locking state stays consistent when you change between split view and editor/preview view.  
This created a new bug: after locking, changing to split view and changing back to editor/preview view, there would be no unlock icon, leaving the user "stuck" in the editor view. In order to fix that, I changed the line 22 of MarkdownEditor.js.  
Finally, fixed a display bug where the lock button was still showing up in the split view.  

simplescreenrecorder-2018-11-29_17 26 21

## Issue fixed
#2121 

## Type of changes
- :radio_button: : Bug fix (Change that fixed an issue)
- :white_circle: :Breaking change (Change that can cause existing functionality to change)
- :white_circle: : Improvement (Change that improves the code. Maybe performance or development improvement)
- :white_circle: Feature (Change that adds new functionality)
- :white_circle: Documentation change (Change that modifies documentation. Maybe typo fixes)

## Checklist:
- :radio_button: My code follows [the project code style](docs/code_style.md)
- :white_circle: I have written test for my code and it has been tested
- :radio_button: All existing tests have been passed
- :white_circle: I have attached a screenshot/video to visualize my change if possible

### CODE REVIEW

**Comment by ZeroX-DG** [comment]
The lock button doesn't seem to display for me anymore.
ss

**Comment by miguelalexbt** [comment]
That's weird. Just tested on both Linux and Windows and it works perfectly. When does it happens?

**Comment by miguelalexbt** [comment]
Synced my fork with upstream and fixed what was probably causing that bug. Can you confirm if it's fixed?

**Comment by ZeroX-DG** [comment]
The lock button has now appeared but it appeared in the wrong way. It appear when the editor is in split view but when I change the mode and change it back, it's gone.
boost_lock

**Comment by miguelalexbt** [comment]
Found the problem: the lock button only works when using BLUR. Working on it.

**Comment by miguelalexbt** [comment]
My bad, completely forgot about being able to switch between preview/editor using double/right click. The issue should be fixed now (tested on both Linux and Windows).

**Comment by ZeroX-DG** [comment]
@miguelalexbt I found another bug. If you change from markdown note to a markdown note, the feature works great! But if you can it to a snippet note before changing to a markdown note, the lock button will disappear!
baasv

**Comment by ZeroX-DG** [comment]
Although I still need @Rokt33r to review this

**Pull request merged**
