### PR TITLE
Add recent translated korean developement & debug docs

### PR DESCRIPTION
**Pull request by voidsatisfaction**
Add recent translation for korean developer

### CODE REVIEW

**Comment by voidsatisfaction** [comment]
I think it is good for adding Korean debug translation with this pull request. So, I will do it right now.

**Comment by kazup01** [comment]
Thanks for your great contribution! @voidsatisfaction 
I can not read Korean, but I trust you. I merged it.

**Comment by voidsatisfaction** [comment]
@kazup01 Thank you for trusting me :D

**Comment by kazup01** [comment]
👍

**Comment by kazup01** [comment]
Hi @voidsatisfaction , could you help #1318? Thanks for your support.

**Comment by voidsatisfaction** [comment]
@kazup01 Okay. I will do that. So, what should I do then?

**Comment by kazup01** [comment]
Thanks :) Could you contribute here? https://github.com/BoostIO/boostio.github.io/blob/master/kr.md

**Comment by voidsatisfaction** [comment]
@kazup01 Okay ~ I will finish it asap(maybe until next week)

**Pull request merged**
