### PR TITLE
Add german documents

### PR DESCRIPTION
**Pull request by kazup01**

### CODE REVIEW

**Comment by kazup01** [comment]
Merged.

**Comment by kazup01** [comment]
Special thanks: Translated by @gino909 ;)

**Comment by kazup01** [comment]
Hi @gino909 , could you help #1318?

**Comment by gino909** [comment]
Hi, happy new year!
Sure I can, if you give me the webdav sync for mobile clients in exchange ;-)
Let me know where I can find the base files and I will do my best.

**Pull request merged**
