### PR TITLE
Update note design

### PR DESCRIPTION
**Pull request by ytk141**
# Update Note Detail style
boostnote notedetail design update copy

### CODE REVIEW

**Comment by ytk141** [comment]
@kazup01 Updated style as you requested

**Comment by kazup01** [comment]
Thank @ytk141 ! I will check it soon ;)

**Comment by kazup01** [comment]
Merged. I will fix CI error soon. Thanks @ytk141 :tada:

**Comment by peci1** [comment]
Sorry, but I don't like this. Could there be an option for it?

**Comment by himaanshu24** [comment]
Now there is more whitespace present on both side of the note, wasting large area to take note. Also, this issue #1091 is still not fixed.

**Comment by ShreyasAiyar** [comment]
Hi could we have an option to toggle this feature?
For some of us with smaller screen sizes it is very not convenient.

**Comment by kazup01** [comment]
There is none option, but we will improve the layout by the next update. Wait a moment.
#1173

**Pull request merged**
