### PR TITLE
Add search-box

### PR DESCRIPTION
**Pull request by asmsuechan**
Because of its high demand, I finally implemented it.
screen shot 2017-07-07 at 17 14 38

### CODE REVIEW

**Comment by huettenhain** [comment]
Absolutely fantastic. Curiosity only: can this do search/replace as well?

**Comment by asmsuechan** [comment]
@huettenhain See.
8752526f0f697b0da7a5a5a83306941e

**Comment by huettenhain** [comment]
Awesome.

**Comment by asmsuechan** [comment]
ref: Replace cm searchbox to official search addon: https://github.com/BoostIO/Boostnote/pull/696

**Comment by yashha** [comment]
Maybe add some spacing to Replace and All

**Comment by asmsuechan** [comment]
Hi, @yashha. The box is no longer used. ref: https://github.com/BoostIO/Boostnote/pull/696

**Pull request merged**
