### PR TITLE
TOC: Scrolling: Fixed TOC links and scrolling

### PR DESCRIPTION
**Pull request by shmolf**
## Description
Fixed the Scrolling when clicking a link from the TOC.

Instead of modifying the overflow for `html`, just needed to change the track's background.
Also, changed a reference on line 1052 to `this.getWindow()`, so it's consistent with a reference shortly there after.

TOC-Scroll-small

## Issue fixed
https://github.com/BoostIO/Boostnote/issues/3287

## Type of changes

- :radio_button: Bug fix (Change that fixed an issue)
- :white_circle: Breaking change (Change that can cause existing functionality to change)
- :radio_button: Improvement (Change that improves the code. Maybe performance or development improvement)
- :white_circle: Feature (Change that adds new functionality)
- :white_circle: Documentation change (Change that modifies documentation. Maybe typo fixes)

## Checklist:

- :radio_button: My code follows [the project code style](docs/code_style.md)
- :white_circle: I have written test for my code and it has been tested
- :radio_button: All existing tests have been passed
- :radio_button: I have attached a screenshot/video to visualize my change if possible

### CODE REVIEW

**Comment by shmolf** [comment]
@Flexo013 Tagging you because you mentioned some work being done [here](https://github.com/BoostIO/Boostnote/issues/3287#issuecomment-546589542)

**Comment by Flexo013** [comment]
> @Flexo013 Tagging you because you mentioned some work being done [here](https://github.com/BoostIO/Boostnote/issues/3287#issuecomment-546589542)

Thanks for the tag and the PR! I think this might already be fixed by #3294. Could you compare these PRs and see if there are any differences or improvements.

**Comment by shmolf** [comment]
They are different solutions for sure. But the other solution does look like improvements. But I haven't actually reviewed the changes thoroughly.

But he corrects the usage of `scrollTo` in `MarkdownPreview.js` to be used against the `window` object.

**Comment by shmolf** [comment]
I recently pulled master from the upstream repository, and it doesn't seem like scrolling is working as expected from the `master` branch. My changes seem to work fine, however.

@Flexo013 Are you experiencing the same thing?

Unexpected behavior from `master`:

master-toc

Expected behavior from `toc-scroll`:
toc-scroll-toc

**Comment by Flexo013** [comment]
@hikerpig @Rokt33r Can either of you confirm that the merged fix from #3294 is not quite sufficient and that this PR is a good fix on top of the previous fix?

**Comment by hikerpig** [comment]
I think #3294 is sufficient for fixing TOC-link-click-scrolling behavior.

But the `::-webkit-scrollbar-track-piece` is much better than my original body-height and html-overflowY tweak for scrollbar styling (#2902).  I should do some cleanup for my old solution.

**Comment by shmolf** [comment]
@hikerpig I recently pulled master into this branch ([yeseterday](https://github.com/BoostIO/Boostnote/pull/3318/commits/8eee3d4679dc5c78d867bb3c506b711f7faa3586), and it includes [your commit](https://github.com/shmolf/Boostnote/commit/77833ff9804efe6b828d4ff3a656777962f0130c).

**Comment by hikerpig** [comment]
@shmolf  Would you mind checking this [commit](https://github.com/hikerpig/Boostnote/commit/44ecd44f0d2408f80b70a8333c81309473622e06) and merge it for your PR ? I've done testing for below scenarios.
1. While `scrollPastEnd` enabled , both preview and split mode should work well and are consistent. (Without my commit, this seems not working)
2. Click TOC link, scrolling to target works well.

**Comment by shmolf** [comment]
With both `Allow editor to scroll past last line` and `Allow preview to scroll past last line` enabled.

image

**Comment by shmolf** [comment]
@hikerpig 
Yep, nevermind. It's not often I merge changes to my branch. I didn't pull into my local machine.

Looks like it works

image

**Comment by shmolf** [comment]
I noticed that your changes weren't in my sandbox. I'm glad it's working now though.

**Comment by shmolf** [comment]
The last screenshot was from scrolling down from the Editor side.  
The screenshot below is from scrolling down on the Preview side.

image

**Comment by shmolf** [comment]
I'm assuming the variance has to do with `offset` or `scrollheight` differences between the two sides.

Does that sound right?

**Comment by shmolf** [comment]
@hikerpig ToC works. Did you experience [this behavior](https://github.com/BoostIO/Boostnote/pull/3318#issuecomment-550135820) from your own fork?

**Comment by hikerpig** [comment]
@shmolf I guess so, bue not quite sure, this difference exists before I initial commit about issue 2902. 

From what I see in Devtools, `.CodeMirror-lines` padding-bottom is calculated during runtime and is represented in px, and MarkdownPreview padding-bottom is written in css `90vh`.

This may need another PR for proper discussions.

**Comment by Flexo013** [comment]
@ZeroX-DG Since you reviewed the previous related PR could you also review this one?

**Comment by shmolf** [comment]
@zerox-dg Are there anything questions or concerns you have about the changes?

**Comment by ZeroX-DG** [comment]
This one look good to me but I haven't tested it yet. Will do it when I get home.

**Pull request merged**
