### PR TITLE
Issue 1706 tag rename - finishing #2989

### PR DESCRIPTION
**Pull request by AWolf81**
## Description

@khaliqgant I hope it's OK that I'm adding the requested changes from your PR #2989.
My PR adds a dialog if the new tag is matching an existing tag and shows a warning dialog.

@ZeroX-DG can you please check if the feature is now like you expect it? Please also check if the copy of the dialog is OK.

Linting issue is present here too. I've commited with `--no-verify` option. Linting will be fixed in my other open PR.
## Issue fixed

#1706

## Type of changes

- :white_circle: Bug fix (Change that fixed an issue)
- :white_circle: Breaking change (Change that can cause existing functionality to change)
- :radio_button: Improvement (Change that improves the code. Maybe performance or development improvement)
- :white_circle: Feature (Change that adds new functionality)
- :white_circle: Documentation change (Change that modifies documentation. Maybe typo fixes)

## Checklist:

- :radio_button: My code follows [the project code style](docs/code_style.md)
- :white_circle: I have written test for my code and it has been tested
- :white_circle: All existing tests have been passed
- 🔘 I have attached a screenshot/video to visualize my change if possible

**Example merge warning (tag was 2nd and renamed to react - react tag already exists)**
grafik

### CODE REVIEW

**Comment by Flexo013** [comment]
@AWolf81 Could you investigate the failing check of the CI?

**Comment by AWolf81** [comment]
@Flexo013 sure, I've checked it and this branch will work on Travis once PR #3465 is merged.

You can see the result on my Travis build [here](https://travis-ci.org/AWolf81/Boostnote/builds). I've created a branch based on `1706-tag-rename` branch and merged the `fix-prettier-setup` branch.
That will fix the CI failure.

**Comment by ZeroX-DG** [comment]
@AWolf81 can you change the style to of the way we currently styling right now? Also the rename modal background doesn't match with some of the theme

**Comment by AWolf81** [comment]
@ZeroX-DG Theme should be OK now. Please have a look. 
I've noticed that it's not looking like the create new folder modal but I think the look is better with just the border below the input instead of the complete white border. But let me know how this should look or if that's OK.

I've noticed one point that could be improved. If you click on a tag to rename and click `confirm` with-out any changes there will be also the merge dialog. What do you think should we handle this and just dismiss the modal with-out the merge dialog?

**Comment by khaliqgant** [comment]
Totally missed the pings, thanks for wrapping this up @AWolf81!

**Pull request merged**
