### PR TITLE
Fix Cmd+Left to go to start of visual line on Mac

### PR DESCRIPTION
**Pull request by rscott**
Addresses #2427

### CODE REVIEW

**Comment by rscott** [comment]
I misread the issue previously and implemented the opposite of the proposed fix. I realized that today and have changed it to #2427's actual request.

**Comment by ZeroX-DG** [comment]
@rscott can you update your PR?

**Comment by ZeroX-DG** [comment]
@rscott ping!

**Comment by Rokt33r** [comment]
I've fixed it. https://github.com/BoostIO/Boostnote/pull/2746

**Pull request closed without merging**
