### PR TITLE
Add Solarized Dark theme

### PR DESCRIPTION
**Pull request by ytk141**
Add Solarized Dark theme

@kazup01 Check it plz

### CODE REVIEW

**Comment by ytk141** [comment]
solarized dark theme color pallete

**Comment by kazup01** [comment]
@ytk141  Cool 😂 I will check it soon!
cool

**Comment by kazup01** [comment]
Thanks for your contribution @ytk141 !
Please check the following.

- Could you add background color when a note is selected at note list?

dec-14-0029 16-42-24

- Please add background color to "Finder" window. (You can open it using `cmd + alt + s`)

screen shot 0029-12-14 at 4 41 46 pm

Thanks!

**Comment by ytk141** [comment]
@kazup01 fixed

**Comment by kazup01** [comment]
Merged. Thank you for your contribution 🎉 @ytk141

**Pull request merged**
