### PR TITLE
add shortcuts to fold blocks

### PR DESCRIPTION
**Pull request by daiyam**
## Description

This change adds the following shortcuts to fold depending on the desired level:

Shortcuts on Window/Linux:
- foldAll: `Control + O`
- unfoldAll: `Control + Shift + O`
- foldLevel1: `Alt + 1`
- foldLevel2: `Alt + 2`
- foldLevel3: `Alt + 3`
- foldLevel4: `Alt + 4`
- foldLevel5: `Alt + 5`
- unfoldLevel1: `Alt + Shift + 1`
- unfoldLevel2: `Alt + Shift + 2`
- unfoldLevel3: `Alt + Shift + 3`
- unfoldLevel4: `Alt + Shift + 4`
- unfoldLevel5: `Alt + Shift + 5`

Shortcuts on macOS:
- foldAll: `Command + O`
- unfoldAll: `Command + Shift + O`
- foldLevel1: `Control + 1`
- foldLevel2: `Control + 2`
- foldLevel3: `Control + 3`
- foldLevel4: `Control + 4`
- foldLevel5: `Control + 5`
- unfoldLevel1: `Control + Alt + 1`
- unfoldLevel2: `Control + Alt + 2`
- unfoldLevel3: `Control + Alt + 3`
- unfoldLevel4: `Control + Alt + 4`
- unfoldLevel5: `Control + Alt + 5`

Shortcuts screen:
screenshot

## Issue fixed

- #1630

## Type of changes

- :white_circle: Bug fix (Change that fixed an issue)
- :white_circle: Breaking change (Change that can cause existing functionality to change)
- :white_circle: Improvement (Change that improves the code. Maybe performance or development improvement)
- :radio_button: Feature (Change that adds new functionality)
- :white_circle: Documentation change (Change that modifies documentation. Maybe typo fixes)

## Checklist:

- :radio_button: My code follows [the project code style](docs/code_style.md)
- :white_circle: I have written test for my code and it has been tested
- :radio_button: All existing tests have been passed
- :radio_button: I have attached a screenshot/video to visualize my change if possible

### CODE REVIEW

**Comment by pihentagy** [comment]
I would prefer other shortcuts, like <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>+</kbd> for expand all.
Also, I wouldn't reserve commands to fold till level x, rather have a "fold more" and "fold less" shortcuts a la vim.

**Comment by pihentagy** [comment]
See http://vimdoc.sourceforge.net/htmldoc/fold.html

**Comment by daiyam** [comment]
@pihentagy You will be able to change them. Even those aren't the ones I'm using...

**Comment by paxcodes** [comment]
What's stopping this from being merged?

**Pull request closed without merging**
