### PR TITLE
Custom background - Editor

### PR DESCRIPTION
**Pull request by shmolf**
## Description
An additional setting is created for the user to provide a path to a background image.
The input takes in a URI like
- `https://example.com/image.png`
- `file:///C:/Users/userName/images/favoriteBackground.png`
The input will inevitably be used in a CSS attribute (`background-image: url(path)`), and so should adhere to the CSS restrictions.

The background is applied to the Editor, and uses CSS's background blending for a translucent appearance.

It is not applied to the Snippets editor, only the Markdown Editor.

~~The background image doesn't update on settings change. Only when CodeMirror is refreshed.
So, switching notes will update the background, but simply changing the setting does not. This is a limitation on my skills, as I've never worked with React before.~~

Background will update when the setting is saved.

~~[Demonstration](https://youtu.be/O_6MP8JRK6M)~~

custom-background

---

I accidently included in this pull request, the addition of `Custom CSS` to the `en.json` file. It was a missing value, but isn't directly related to the new feature.

## Type of changes

- :radio_button: Bug fix (Change that fixed an issue)
- :white_circle: Breaking change (Change that can cause existing functionality to change)
- :white_circle: Improvement (Change that improves the code. Maybe performance or development improvement)
- :radio_button: Feature (Change that adds new functionality)
- :white_circle: Documentation change (Change that modifies documentation. Maybe typo fixes)

## Checklist:

- :radio_button: My code follows [the project code style](docs/code_style.md)
- :white_circle: I have written test for my code and it has been tested
- :radio_button: All existing tests have been passed
- :radio_button: I have attached a screenshot/video to visualize my change if possible

### CODE REVIEW

**Comment by shmolf** [comment]
@Flexo013 I don't know if you're the appropriate person to ask...
Is this merge holding on something?

**Comment by shmolf** [comment]
In the most recent commit, I've fixed the issue of the background not updating immediately upon change. Also found some bad variable references from one of my prior commits.

custom-background

**Comment by Flexo013** [comment]
There are quite a few PRs awaiting a review, so the highest priority ones get picked up first.

Also, I don't think anybody requested this feature (there is no GitHub issue for it). So this might be considered a feature that is too much bloat, but that is up to the reviewers/community. It could be worth to make a discussion/feature request issue to see if people want this.

As a final note, is this not already sufficiently achievable with the custom CSS?

**Comment by shmolf** [comment]
I will create a Feature Request. Is there a good medium/channel to present it, or just allow for natural discovery from the community?

Also, the custom CSS is specific to the Preview side. [Config supports this](https://github.com/BoostIO/Boostnote/blob/master/browser/main/modals/PreferencesModal/UiTab.js#L924)

**Comment by shmolf** [comment]
Created the Feature Request issue: https://github.com/BoostIO/Boostnote/issues/3343

**Comment by arcturus140** [comment]
you can link to the feature request in slack channel

**Comment by ZeroX-DG** [comment]
Close due to considered as bloat by community :(

**Pull request closed without merging**
