### PR TITLE
[WIP] Improve search popup

### PR DESCRIPTION
**Pull request by asmsuechan**
I'm improving search popup.

screen shot 2017-03-22 at 18 11 20

### CODE REVIEW

**Comment by kazup01** [comment]
Great! I will also consider to improve it.

**Comment by asmsuechan** [comment]
Do anyone have any ideas to highlight the matched words?

**Comment by huettenhain** [comment]
Since you say that you're working on the search bar, I just wanted to mention [my previous suggestion](https://github.com/BoostIO/Boostnote/issues/152) because I'd be really excited about having that.

**Comment by asmsuechan** [comment]
@huettenhain absolutely true. Does it mean like this?
screen shot 2017-03-23 at 21 03 39

**Comment by asmsuechan** [comment]
I assume it's not good. So I close this PR.

**Comment by huettenhain** [comment]
Sorry, I was just busy over the weekend, actually this looks awesome, why did you delete the branch?

**Comment by asmsuechan** [comment]
@huettenhain No problem :smile: Because I'd like to improve the search like that picture.

**Pull request closed without merging**
