### PR TITLE
Fix issue #2931

### PR DESCRIPTION
**Pull request by uS-aito**
## Description
This PR fixes issue #2931 

## Issue fixed

decodeEntities function is enabled to code block in MarkdownPreview.js.
Disabled it.

## Type of changes

- :black_circle: Bug fix (Change that fixed an issue)
- :white_circle: Breaking change (Change that can cause existing functionality to change)
- :white_circle: Improvement (Change that improves the code. Maybe performance or development improvement)
- :white_circle: Feature (Change that adds new functionality)
- :white_circle: Documentation change (Change that modifies documentation. Maybe typo fixes)

## Checklist:

- :black_circle: My code follows [the project code style](docs/code_style.md)
- :white_circle: I have written test for my code and it has been tested
- :black_circle: All existing tests have been passed
(Is this item means run `npm run test`? I read docs but could not find a way to test.)
- :black_circle: I have attached a screenshot/video to visualize my change if possible
image

I read contributing.md, but please point out any pull requests that are incomplete.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Referenced issues

This pull request has been submitted to:
- [#2931: `&lt;` will be rendered as `<`](https://issuehunt.io/repos/53266139/issues/2931)
---

IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### CODE REVIEW

**Comment by ZeroX-DG** [comment]
Disabling this will cause the renderer to render html entities wrong. I'll close this for now. Feel free to re-open this when you have a better solution.

**Comment by uS-aito** [comment]
Thank you for your review, @ZeroX-DG .

This pull request only affects the code block.
You said that wrong renders may occur, but issue #2931 does not convert notations such as `&lt;` into symbols, but asks to output them as they are.

In my opinion, this pull request satisfies this request and seems to have no effect on others.
Could you tell me what is wrong?
image

**Comment by ZeroX-DG** [comment]
Sorry for not give more information in my review. Right now if you try to write a simple html code to the code like this:
```
<h1>Hello</h1>
```
It should render with `<` and `>` intact. But after applying your PR this is how it will look like:
```
&lt;h1&gt;hello&lt;/h1&gt;
```
That's why I think you need to have a better way to deal with this.

**Comment by uS-aito** [comment]
Thank you for your info, @ZeroX-DG .

It was reproduced in my local. It's wrong.
I want to think about better PR.
This PR is tagged as awaiting changes. Is it better to create a new PR?

**Comment by ZeroX-DG** [comment]
You can push your new code up here on this PR if you want to:)

**Comment by ZeroX-DG** [comment]
@uS-aito have you finished this PR yet? I think the code looks quite strange but if yes I'll test this when I get home.

**Comment by uS-aito** [comment]
@ZeroX-DG No, the code hasn't changed yet.
Unfortunately, I could not solve this problem.

**Comment by ZeroX-DG** [comment]
No worries. I'll close this for now, feel free to re-open once you come up with a solution

**Pull request closed without merging**
