### PR TITLE
export folder should also export the attachments -> fixes #2374

### LINKED ISSUE #2374: export folder as markdown with pictures
# Current behavior
If I write a note in Boostnote and i insert picture(s) in this note ,when i choose to export this note as markdown file,i will see that these pictures are missing(pictures are not copied to the destination folder and the picture  link in markdown file are not changed )

# Expected behavior
all the pictures are exported to destination folder and the link in md file are changed to correct
# Steps to reproduce

# Environment

- Version : 0.11.9
- OS Version and name :win10 pro

### PR DESCRIPTION
**Pull request by ehhc**

### CODE REVIEW

**Comment by ehhc** [comment]
@ZeroX-DG can you pleasae have a look at this :)

**Comment by ehhc** [comment]
@Rokt33r can you have a look at this PR? :)

**Comment by ZeroX-DG** [comment]
Sorry for the delay, I look at this today.

**Comment by ZeroX-DG** [comment]
Should we skip exporting empty note? Because if the note is empty your code will still export it to a `.md` file (the file has no name, just `.md` :smile: )

**Comment by ehhc** [comment]
@ZeroX-DG i think that's a separated problem. I didn't implemented the export feature, i just fixed that it can export the attachments as well..
So i think the problem of empty notes should be done independently :)

**Pull request merged**
