### PR TITLE
Introduce formatting hotkeys 

### LINKED ISSUE #3142: Introduce hotkeys for formatting
(This suggestion was originally made by #234)

Having more keyboard shortcuts for often used actions like introducing bold would be great. These actions could all have a hotkey:
- Bold
- Italics
- Inline code
- Code block

Once this feature is implemented it would be nice to have these hotkeys also listed in the preferences so the user can configure them to their own liking.

Related to: #2645

### PR DESCRIPTION
**Pull request by Olcod**
## Description
Introducing hotkeys for formatting.

This is still WIP though.

## Issue fixed
#3142 

## Type of changes

- :white_circle: Bug fix (Change that fixed an issue)
- :white_circle: Breaking change (Change that can cause existing functionality to change)
- :white_circle: Improvement (Change that improves the code. Maybe performance or development improvement)
- :white_circle: Feature (Change that adds new functionality)
- :white_circle: Documentation change (Change that modifies documentation. Maybe typo fixes)

## Checklist:

- :white_circle: My code follows [the project code style](docs/code_style.md)
- :white_circle: I have written test for my code and it has been tested
- :white_circle: All existing tests have been passed
- :white_circle: I have attached a screenshot/video to visualize my change if possible

### CODE REVIEW

**Comment by Olcod** [comment]
Asking for advice here.

While working on this encountered a couple of conflicts with the hotkeys.
For example Ctrl + I is already assigned, and Ctrl + ` doesn't seem to be handled by Electron, and is forwarded to the OS instead.

Which hotkeys you think would work here.

**Comment by Flexo013** [comment]
@Olcod  Could you fix the issues I mentioned?

**Comment by Olcod** [comment]
> @Olcod Could you fix the issues I mentioned?

Sorry, I'm overseas at the moment, so have a limited time available.

I'll update this some time this week.

**Comment by ZeroX-DG** [comment]
@Olcod ping!

**Comment by ZeroX-DG** [comment]
@Olcod ping 2

**Comment by ZeroX-DG** [comment]
Close due to inactivity

**Pull request closed without merging**
