### PR TITLE
Add counter on deleted notes

### PR DESCRIPTION
**Pull request by PaulRosset**
* Add counter to see how many notes are in the trash.

boostnotecounterdeletednotess

### CODE REVIEW

**Comment by kazup01** [comment]
Hi @PaulRosset , thank you for always your contributing!

I think that "All Notes" and Starred" also have this feature better than "Trash" alone.  
How about do you think?

**Comment by kazup01** [comment]
Hi @PaulRosset !
This(https://github.com/BoostIO/Boostnote/pull/1052/commits/875c4512212e4d04cc499c2305dfdf4f77d91388) is exactly what I meant.
Thank you for your support. We will check it soon!

**Comment by sota1235** [comment]
@PaulRosset 
[Question] Why don't you show the number of each categories when the number is zero?

**Comment by PaulRosset** [comment]
Hi @sota1235 

This is my personal point of view,  Less there is data on the UI more UI will fit for the user.
I prefer to use app which are pure.
So by adding always "0", it is an useless data for the user to know that.

**Comment by kazup01** [comment]
Hi @PaulRosset ! Thank you for your reply.
We think that it is better to show "0" because it is displayed in the case of Folder. 
What do you think about it?
 
screen shot 0029-11-06 at 9 06 09 am

**Comment by PaulRosset** [comment]
Oh ok, it make sense.
It is edited in the last commit.

**Comment by kazup01** [comment]
Thank you for your quick response and great support :) We will check it!

**Comment by kazup01** [comment]
Merged. Thank you for your contribution @PaulRosset 🎉

**Comment by kazup01** [comment]
Hi @PaulRosset , I wrote your pull request to [release note](https://medium.com/boostnote/thanks-to-your-contribution-boostnote-v0-8-17-is-out-5fea9c7727f2).
Thank you again :)

**Pull request merged**
