### PR TITLE
Add save-to-pdf button

### PR DESCRIPTION
**Pull request by ivz-dev**
screenshot_20171027_003726

### CODE REVIEW

**Comment by kazup01** [comment]
Thanks for your contribution @ivz-dev ! Could you review this? @asmsuechan

**Comment by kazup01** [comment]
Hi @ivz-dev , could you commit yarn.lock?

**Comment by NamedKitten** [comment]
Please commit `yarn.lock`.

**Comment by kazup01** [comment]
Hi @ivz-dev , could you fix it? Thank you for your contribution!

**Comment by kazup01** [comment]
I close it because long absence. If someone want to reopen, please feel free to talk to us.

**Pull request closed without merging**
