### PR TITLE
[Feature] Add support for plantUML mindmap, wbs, gantt

### PR DESCRIPTION
**Pull request by MSSandroid**
## Description
I have added supprt for mindmap, wbs and gantt charts in plantuml. I just copied the part for the part for Ditaa chart and change the @ indicators and switched to svg output.
 I havent added any tests, since I am not shure how. Test and lint have same output as current master

## Type of changes

- :white_circle: Bug fix (Change that fixed an issue)
- :white_circle: Breaking change (Change that can cause existing functionality to change)
- :white_circle: Improvement (Change that improves the code. Maybe performance or development improvement)
- :white_check_mark: Feature (Change that adds new functionality)
- :white_circle: Documentation change (Change that modifies documentation. Maybe typo fixes)

## Checklist:

- :white_check_mark: My code follows [the project code style](docs/code_style.md)
- :white_circle: I have written test for my code and it has been tested
- :white_check_mark: All existing tests have been passed
- :white_check_mark: I have attached a screenshot/video to visualize my change if possible

Screenshot_20190518_145129

### CODE REVIEW

**Comment by Komalis** [comment]
What is taking this long to review?

**Comment by ZeroX-DG** [comment]
Hi, sorry for the late review. @MSSandroid Can you add a simple snapshot test? Just add the test to this file and delete the snap file in the same directory and run `yarn test` to test it.
https://github.com/BoostIO/Boostnote/blob/master/tests/lib/snapshots/markdown-test.js.md

**Comment by MSSandroid** [comment]
I have now added separate tests for the different diagram types. Sorry for the delay.

**Comment by ZeroX-DG** [comment]
@MSSandroid Can you fix the conflict before I approve your code?

**Comment by Flexo013** [comment]
@MSSandroid is there a particular reason why you closed this MR?

**Comment by MSSandroid** [comment]
I falsely deleted the branch in my fork.... Reopened a copy in [pull request # 3249](https://github.com/BoostIO/Boostnote/pull/3249)

**Pull request closed without merging**
