### PR TITLE
macOS - Title Bar & Dark Color Theme

### LINKED ISSUE #1055: Feature Request: macOS - Title Bar & Dark Color Theme
Is it possible that the Title Bar switches to dark mode, if the "Dark Color Theme" is enabled via preferences?

Screenshot 1) Light Theme with light title bar
macos_title_bar_light

Screenshot 2) Dark Theme with light title bar
macos_title_bar_dark

Screenshot 3) Dark title bar in other Editor
title_bar_dark

### PR DESCRIPTION
**Pull request by mikaoelitiana**
fixes #1055

work-in-progress

### CODE REVIEW

**Comment by mikaoelitiana** [comment]
@Rokt33r yes I made all requested changes from previsou PR

**Comment by Rokt33r** [comment]
screen shot 2018-09-15 at 11 47 19
It doesn't work on Windows. Is it possible for you to enable it on only macOS?

**Comment by mikaoelitiana** [comment]
@Rokt33r I will check that (sorry didn't have Windows to test)

**Comment by yougotwill** [comment]
Any updates on this @mikaoelitiana? :)

**Comment by mikaoelitiana** [comment]
@yougotwill I added a condition to make it used on osx only.

**Comment by Rokt33r** [comment]
@mikaoelitiana Could you fix the conflicts?

**Comment by mikaoelitiana** [comment]
Yes I fixed conflicts

**Comment by georgeherby** [comment]
Did this PR just get forgotten or did it get added elsewhere?

**Comment by Flexo013** [comment]
Obsolete due to #2509

**Pull request closed without merging**
