### PR TITLE
Fixes syntax hilight of inline code on Preview

### PR DESCRIPTION
**Pull request by asmsuechan**
Hi, I fixed the bug reported by https://github.com/BoostIO/Boostnote/issues/208.

I referenced GitHub for this style.

### CODE REVIEW

**Comment by asmsuechan** [comment]
Hmm

**Comment by sota1235** [comment]
That's more easy to read! But I think it can be more easy to read.
For example, color of the text is `CC305F`, it's like below.





I think changing color of the text is easy and best way.
How about you?

**Comment by asmsuechan** [comment]
It looks so good! I'll change the code.

**Comment by asmsuechan** [comment]
How about them?

**Comment by sota1235** [comment]
That's so cool.
Looks good to me!

**Pull request merged**
