### PR TITLE
Fix app name and icon on linux

### PR DESCRIPTION
**Pull request by sferra**
Follow-up on [pull request 534](https://github.com/BoostIO/Boostnote/pull/543)
Sorry for the delay.

### CODE REVIEW

**Comment by yashha** [comment]
Thanks! LGTM, just checked it

**Comment by kazup01** [comment]
Thanks @sferra !

**Comment by yashha** [comment]
Wait the application name is "Electron" on my test?

**Comment by sferra** [comment]
@yashha I am AFK for the next 24 hours, so I'm afraid I can't verify that.
Could you please disable dash-to-dock (just for testing)  and check if the effect is the same?

**Comment by yashha** [comment]
Same when it is deactivated.
screenshot from 2017-08-15 14-32-41

**Comment by sferra** [comment]
I'll verify as soon as possible.

**Comment by yashha** [comment]
Maybe it changes, when packageing and installing it.
On run-dev it it like that.

**Comment by yashha** [comment]
It works after packaging.
screenshot from 2017-08-15 15-20-56
So lgtm.

**Comment by sferra** [comment]
Thank you for testing. Please let me know if there is anything else I can do.

**Comment by asmsuechan** [comment]
# environment
Ubuntu 16.04 LTS

# before
`yarn run dev-start`
image

`grunt pre-build`
image

# after
`yarn run dev-start`
screenshot from 2017-08-18 18-05-00

`grunt pre-build`
screenshot from 2017-08-18 18-40-28

**Pull request merged**
