### PR TITLE
Create a image tag when pasting image url

### PR DESCRIPTION
**Pull request by kawmra**
# My proposal

When we paste a url, a link tag is automatically created with the fetched title.
It is very useful!

But in case of pasting a image url, the created link tag is just a link tag.
I think it is more useful if image tag is created if pasted url is image's.

## Before

create-image-tag-before

## After

create-image-tag-after

### CODE REVIEW

**Comment by sosukesuzuki** [comment]
@kawmra Please fix conflict!!

**Comment by kawmra** [comment]
@sosukesuzuki 
Of course!
But could you merge [this PR](https://github.com/BoostIO/Boostnote/pull/2024) at first?
Because the yarn.lock file has changed by running `yarn` command to debug merged  code.

**Comment by sosukesuzuki** [comment]
@kawmra I merged #2024! Please resolve the remaining conflicts.

**Comment by kawmra** [comment]
@sosukesuzuki
Thank you!
I will work on this tonight (JST) 😁

**Comment by kawmra** [comment]
@sosukesuzuki Resolved!

**Pull request merged**
