### PR TITLE
 add support to abbreviations, definition lists and subscript/superscript text

### PR DESCRIPTION
**Pull request by daiyam**
This change adds support of:
- abbreviations
- subscript text
- superscript text
- definition lists (allow empty definition)

screenshot

### CODE REVIEW

**Comment by daiyam** [comment]
@Rokt33r I've resolved the conflicts

**Comment by Rokt33r** [comment]
@daiyam Could you fix the conflicts again? I'm sorry for being late.. 😢

**Comment by daiyam** [comment]
@Rokt33r I've made the merge but I wasn't able to test. On the master, when I do `yarn dev`, I'm getting `Electron: bad option: --hot` out of the blue... or on an older version, it doesn't start... I did broken something on my machine...

**Comment by Rokt33r** [comment]
@daiyam Could you try to remove `node_modules` and execute `yarn` again? Btw, I'll test it by myself. :)

**Comment by Rokt33r** [comment]
Okay! And I've tested this now. It looks Awesome! 💯

**Pull request merged**
