### PR TITLE
Strip HTML tags from the note title

### PR DESCRIPTION
**Pull request by xxdavid**
I'd like to style my headings with a color. The problem is the HTML tags aren't stripped from the title. This PR fixes it.

Before:
Before

After:
After

### CODE REVIEW

**Comment by kazup01** [comment]
Merged. Thanks for your contribution @xxdavid !🎉

**Comment by kazup01** [comment]
Would you like to try [Boostnote Mobile](https://github.com/BoostIO/Boostnote-mobile) ? @xxdavid

**Comment by xxdavid** [comment]
Thank you. :)

**Comment by xxdavid** [comment]
@kazup01, sorry, I don't get it... What do you mean by trying?

**Pull request merged**
