### PR TITLE
Better scroll sync between the editor and the preview in the SplitEditor

### PR DESCRIPTION
**Pull request by daiyam**
## Description

This change implements better positioning between the editor and the preview in the SplitEditor (particularly with lot of images).

When scrolling, it calculates the position of the shown block (at 1/3 below the top) based on the previous blocks' heights.
When the cursor is active, the preview is moved at a position so we can see what we are typing.

## Issue fixed

- #2734
- #2561

## Type of changes

- :radio_button: Bug fix (Change that fixed an issue)
- :white_circle: Breaking change (Change that can cause existing functionality to change)
- :radio_button: Improvement (Change that improves the code. Maybe performance or development improvement)
- :white_circle: Feature (Change that adds new functionality)
- :white_circle: Documentation change (Change that modifies documentation. Maybe typo fixes)

## Checklist:

- :radio_button: My code follows [the project code style](docs/code_style.md)
- :white_circle: I have written test for my code and it has been tested
- :radio_button: All existing tests have been passed
- :white_circle: I have attached a screenshot/video to visualize my change if possible

### CODE REVIEW

**Comment by daiyam** [comment]
I've tested it with the preferences `scroll past the last line`.
I've added the support to the preference `When scrolling, synchronize preview with editor`.

It's working fine.

**Comment by Shagon94** [comment]
Would love to see this be added, its really hard to navigate when viewing side by side due to inconsistency between the live preview and the text itself

**Comment by Aaron-Bird** [comment]
Was this pr abandoned?

**Comment by daiyam** [comment]
@Aaron-Bird not by me 😉

**Comment by ZeroX-DG** [comment]
Sorry for not being able to review this soon, I'll try to work on this when I have time.

**Comment by hzhangxyz** [comment]
is there any update for this pr?

**Comment by ZeroX-DG** [comment]
@daiyam sorry for the wait, can you resolve conflict for this PR please?

**Comment by daiyam** [comment]
@ZeroX-DG I've resolved the conflicts

**Comment by ZeroX-DG** [comment]
@daiyam the feature does work well but one bug that I found is if you don't separate the lines with an empty line. The whole thing will be rendered as a paragraph with each line separate with `<br>` and the `data-line` is `0`. This will make the preview doesn't scroll at all when it encounter multiple sticky line.
Peek 2020-05-16 16-21

**Comment by daiyam** [comment]
@ZeroX-DG I've pushed a fix. Can you test it?

**Comment by arcturus140** [comment]
@daiyam i Think that this pull request is still maintained after almost 2 years deserves some mention. 😮
you're awesome!

**Pull request merged**
