### PR TITLE
improve autocomplete within code blocks

### PR DESCRIPTION
**Pull request by daiyam**
## Description

This change separates the autocomplete's configuration between generic markdown and with code blocks.
It allows to disable autocomplete on `*` or `$` characters in code blocks.

## Issue fixed

- #2221

## Type of changes

- :white_circle: Bug fix (Change that fixed an issue)
- :white_circle: Breaking change (Change that can cause existing functionality to change)
- :radio_button: Improvement (Change that improves the code. Maybe performance or development improvement)
- :white_circle: Feature (Change that adds new functionality)
- :white_circle: Documentation change (Change that modifies documentation. Maybe typo fixes)

## Checklist:

- :radio_button: My code follows [the project code style](docs/code_style.md)
- :white_circle: I have written test for my code and it has been tested
- :radio_button: All existing tests have been passed
- :white_circle: I have attached a screenshot/video to visualize my change if possible

### CODE REVIEW

**Comment by daiyam** [comment]
I've added the support for the new preferences fields introduced by #2586

screenshot

**Comment by Rokt33r** [comment]
I'm going to review this in this weekend.

**Comment by ZeroX-DG** [comment]
@daiyam can you resolve conflict please? :+1:

**Comment by daiyam** [comment]
@ZeroX-DG Here you are are ;) I've even used the newest version of of the addon `closebrackets.js` which adds the new option `closeBefore `.
You can read more about it at https://github.com/codemirror/CodeMirror/commit/0c5c59c23d612d8e9a0e7fd74b1efd3643de45de

**Pull request merged**
