### PR TITLE
Fix layout

### PR DESCRIPTION
**Pull request by kazup01**
Before:
screen shot 0029-07-09 at 12 49 29 pm

After:
screen shot 0029-07-09 at 12 50 16 pm

### CODE REVIEW

**Comment by asmsuechan** [comment]
Personally, it might be better to put the `Search` text inside the input tag.

**Comment by kazup01** [comment]
screen shot 0029-07-08 at 3 58 19 pm

**Comment by kazup01** [comment]
Fix star position at NoteList

screen shot 0029-07-08 at 4 05 26 pm

**Comment by asmsuechan** [comment]
It overlaps the tag area.
screen shot 2017-07-08 at 16 38 28

**Comment by kazup01** [comment]
Tag area at NoteList

screen shot 0029-07-09 at 12 46 23 pm

**Pull request merged**
