### PR TITLE
Cm close brackets

### PR DESCRIPTION
**Pull request by sosukesuzuki**
I implemented one of the #1390 with a codemirror addon.
You enter a bracket, editor close a bracket automatically.

### CODE REVIEW

**Comment by jalalmostafa** [comment]
Thanks for implementing one of the features. It is awesome!

**Comment by ericchang00** [comment]
@sosukesuzuki This may be nontrivial to implement since AFAIK there is no codemirror addon for it, but do you thinkautoclosing backticks and asterisks would be a worthwhile feature? My thought is that when editing markdown, we frequently enclose expressions in backticks for code blocks, and asterisks for `*italic* **bold**`.

**Comment by Rokt33r** [comment]
@ericchang00 It should be nice to have. Could you create an issue for it?

**Comment by tewe** [comment]
Thanks for adding this! How can I disable it?

**Comment by Rokt33r** [comment]
@tewe It is not possible for now. How about you to try to implement it?

**Pull request merged**
