### PR TITLE
Translate contributing.md to Simplified Chinese

### PR DESCRIPTION
**Pull request by KuangLei**
I translated the `contributing.md` to Simplified Chinese.  

Thanks.

### CODE REVIEW

**Comment by asmsuechan** [comment]
Hi, @KuangLei. Cool! Thank you so much! 
Do you mind if I ask you to translate .mds in `docs`, too?

**Comment by KuangLei** [comment]
@asmsuechan I'd love to do it.

**Comment by asmsuechan** [comment]
@KuangLei I really appreciate you :smile:

**Comment by KuangLei** [comment]
@asmsuechan Do you know in Markdown we cannot use a line break but two spaces at the end of a line to make up a new line?  

Thanks.

**Comment by KuangLei** [comment]
@asmsuechan at the top of [build.md](https://github.com/BoostIO/Boostnote/blob/master/docs/build.md), it says  

> You should use `npm v4.x` because `$ grand pre-build` fails on `v5.x`.

but at the bottom it says  

> This build doesn't work on npm v5.3.0. So you need to use v5.2.0 when you build it.

so should people use npm v4.x or v5.2.0? Is it a conflict?  

Thanks.

**Comment by KuangLei** [comment]
All translated.  
If those documents are once updated, you can call me in this pull request or email me at klsz@outlook.com.  

Btw, I would also like to translate all the content in the Boostnote if you want.  

Thanks.

**Comment by kazup01** [comment]
Thanks @KuangLei 😄👍

**Comment by KuangLei** [comment]
@asmsuechan @kazup01 Can I make a mirrors site like [this](http://boostnote-mirrors-china.nos-eastchina1.126.net/) in China? You know Chinese have pitiful connection speed to GitHub because of the GFW.  

Thanks.

**Comment by kazup01** [comment]
Your kindness is very appreciated! @KuangLei 
I have some questions, so please let me ask you.

- How much does it cost to maintain mirror sites?
- Is it possible to paste the latest download link every time the application is updated?

Thank you!

**Comment by KuangLei** [comment]
* This mirrors site is only an Object Storage which has a small free quota, so it cost little, about 5 CNY (83 JPY) a month at most I think. At least for this year I can afford all the expenses if there aren't too much downloads.
* Yes, I've create a `.py` file. Every time the application is updated, you can put the binary files and the `.py` file in a same folder, and then run the `.py` file to upload.  
May I ask you if you have a email? Because there are Access Key and Secret Key in the `.py` file, so I couldn't send it to you on GitHub, sorry.

I'm sorry I don't have the money to buy a domain name, so I may only use direct link. Is that fine?  
And can you provide a link from you [download page](https://boostnote.io/#download) to it?  

Thanks.

**Comment by asmsuechan** [comment]
@KuangLei Sorry for my long absence.

> May I ask you if you have a email?

My email rests on my GitHub page.

> I'm sorry I don't have the money to buy a domain name

No problem.

> And can you provide a link from you download page to it?

Sure.

**Comment by KuangLei** [comment]
@asmsuechan I've sent an email to you with the file to upload. Please check it.  

Thanks.

**Comment by KuangLei** [comment]
@asmsuechan 
Sorry, for now I cannot update the mirrors site due to no connection to GitHub releases.  
Btw, when do you plan to give this mirrors site the first batch of users?  

Thanks.

**Pull request merged**
