### PR TITLE
Localization

### PR DESCRIPTION
**Pull request by SiSchae**
This is an approach to a multi language Interface as suggested in #1252. I started to implement a german translation. Other languages can be added easily.

### CODE REVIEW

**Comment by Rokt33r** [comment]
@SiSchae Did you finished?

**Comment by SiSchae** [comment]
yes, I'm done

**Comment by romainwn** [comment]
Hey I'll be working on the french translation asap 👍

**Comment by SiSchae** [comment]
I'll set the standard language to en and push it to my repo. I extracted the strings as they occur. Some occur in lowercase and some in uppercase in the source code.

What additional languages would you like to see? I would add them, so they only need to be translated.

**Comment by romainwn** [comment]
As mentioned in #1252 , @ranaegis wanted support for Norwegian. Maybe @Rokt33r would love to add Korean support as well ?

Even better, we could create templates for all the languages supported on [Boostnote website](https://boostnote.io/)
So : 
- [x]  English
- [x] German (not on the website, but feel free to to the german translation :smile: )
- [ ]  Chinese (zh-CN)
- [ ]  Chinese (zh-TW)
- [ ]  Japanese
- [ ]  Portugese
- [ ]  Albanian
- [x]  French
- [ ]  Korean
- [ ]  Polish
- [ ]  Spanish
- [ ]  Danish

**Comment by Rokt33r** [comment]
> Maybe @Rokt33r would love to add Korean support as well ?

I'll do Japanese and Korean.

**Comment by SiSchae** [comment]
I added the languages. Let the translation begin :wink: 

Btw: feels nice to work with you! :smiley:

**Comment by romainwn** [comment]
Ok I'm done with the french translation ! 😄

**Comment by Rokt33r** [comment]
@SiSchae I assume we need to use English by default. But, I found it uses Albanian at the first time.

Could you fix this?

screen shot 2018-03-12 at 11 23 07 am

**Comment by SiSchae** [comment]
Should work now. I forgot to set the default language in the DEFAULT_CONFIG. Can you test the new commit?

**Comment by gerd2002** [comment]
I am happy to help with translations, if there is additional help required for German.

**Comment by nlopin** [comment]
I can do Russian

**Comment by bendo** [comment]
Hi, I can do localization to Slovak language.

**Comment by lfromanini** [comment]
I can translate it to Brazilian Portuguese. By the way, I took a look at the Json file and, if you allow me, my recommendation is to rename it to pt-br.json, so you can also have pt-pt for Portuguese from Portugal, which is a little bit different from Brazilian Portuguese. Just add me to the team if you want.

**Comment by SiSchae** [comment]
It's a good idea to rename the *.json files. You can fork the repo and add your changes to the code. Once you are done, open a pull request.

**Comment by lfromanini** [comment]
Done! ;)

https://github.com/BoostIO/Boostnote/pull/1747

**Comment by davidmigloz** [comment]
I've just localized Boosnote to Spanish (#1748) :)

**Pull request merged**
