### PR TITLE
Dracula theme

### PR DESCRIPTION
**Pull request by yougotwill**
New UI theme with colors taken from the [dracula theme](https://github.com/dracula/dracula-theme).

vamp

dracula

**Note** Tags are now cyan see comments below

### CODE REVIEW

**Comment by kazup01** [comment]
Cool!💯💯💯💯

**Comment by ZeroX-DG** [comment]
I think green doesn't suit with the tag. But it looks cool anyway!
image

**Comment by yougotwill** [comment]
@ZeroX-DG Looking at it I agree with you so I've made some alternative versions. What do you think? Personally I think cyan looks good. 😊 

cyan
yellow
pink
orange
purple

**Comment by Rokt33r** [comment]
@yougotwill Could you fix the conflicts?

**Comment by kazup01** [comment]
hey @yougotwill , I featured your contribution on release blog! 
https://medium.com/boostnote/boostnote-v0-11-10-release-on-halloween-9bbe6d488fe8

Dracula theme is so cool, so I'm using right now😄 Thank you!

**Comment by yougotwill** [comment]
Wow thanks @kazup01! I've never been on a medium post before 😂. Glad you liked the theme!

**Pull request merged**
